export type CountryEntry = {
  iso: string;
  nameAr: string;
  nameEn: string;
  callingCode: string;
};

export const COUNTRIES: CountryEntry[] = [
  { iso: "AF", nameAr: "أفغانستان", nameEn: "Afghanistan", callingCode: "+93" },
  { iso: "AL", nameAr: "ألبانيا", nameEn: "Albania", callingCode: "+355" },
  { iso: "DZ", nameAr: "الجزائر", nameEn: "Algeria", callingCode: "+213" },
  { iso: "AD", nameAr: "أندورا", nameEn: "Andorra", callingCode: "+376" },
  { iso: "AO", nameAr: "أنغولا", nameEn: "Angola", callingCode: "+244" },
  { iso: "AG", nameAr: "أنتيغوا وباربودا", nameEn: "Antigua and Barbuda", callingCode: "+1-268" },
  { iso: "AR", nameAr: "الأرجنتين", nameEn: "Argentina", callingCode: "+54" },
  { iso: "AM", nameAr: "أرمينيا", nameEn: "Armenia", callingCode: "+374" },
  { iso: "AU", nameAr: "أستراليا", nameEn: "Australia", callingCode: "+61" },
  { iso: "AT", nameAr: "النمسا", nameEn: "Austria", callingCode: "+43" },
  { iso: "AZ", nameAr: "أذربيجان", nameEn: "Azerbaijan", callingCode: "+994" },
  { iso: "BS", nameAr: "باهاماس", nameEn: "Bahamas", callingCode: "+1-242" },
  { iso: "BH", nameAr: "البحرين", nameEn: "Bahrain", callingCode: "+973" },
  { iso: "BD", nameAr: "بنغلاديش", nameEn: "Bangladesh", callingCode: "+880" },
  { iso: "BB", nameAr: "باربادوس", nameEn: "Barbados", callingCode: "+1-246" },
  { iso: "BY", nameAr: "بيلاروسيا", nameEn: "Belarus", callingCode: "+375" },
  { iso: "BE", nameAr: "بلجيكا", nameEn: "Belgium", callingCode: "+32" },
  { iso: "BZ", nameAr: "بليز", nameEn: "Belize", callingCode: "+501" },
  { iso: "BJ", nameAr: "بنين", nameEn: "Benin", callingCode: "+229" },
  { iso: "BT", nameAr: "بوتان", nameEn: "Bhutan", callingCode: "+975" },
  { iso: "BO", nameAr: "بوليفيا", nameEn: "Bolivia", callingCode: "+591" },
  { iso: "BA", nameAr: "البوسنة والهرسك", nameEn: "Bosnia and Herzegovina", callingCode: "+387" },
  { iso: "BW", nameAr: "بوتسوانا", nameEn: "Botswana", callingCode: "+267" },
  { iso: "BR", nameAr: "البرازيل", nameEn: "Brazil", callingCode: "+55" },
  { iso: "BN", nameAr: "بروناي", nameEn: "Brunei", callingCode: "+673" },
  { iso: "BG", nameAr: "بلغاريا", nameEn: "Bulgaria", callingCode: "+359" },
  { iso: "BF", nameAr: "بوركينا فاسو", nameEn: "Burkina Faso", callingCode: "+226" },
  { iso: "BI", nameAr: "بوروندي", nameEn: "Burundi", callingCode: "+257" },
  { iso: "KH", nameAr: "كمبوديا", nameEn: "Cambodia", callingCode: "+855" },
  { iso: "CM", nameAr: "الكاميرون", nameEn: "Cameroon", callingCode: "+237" },
  { iso: "CA", nameAr: "كندا", nameEn: "Canada", callingCode: "+1" },
  { iso: "CV", nameAr: "الرأس الأخضر", nameEn: "Cape Verde", callingCode: "+238" },
  { iso: "CF", nameAr: "جمهورية أفريقيا الوسطى", nameEn: "Central African Republic", callingCode: "+236" },
  { iso: "TD", nameAr: "تشاد", nameEn: "Chad", callingCode: "+235" },
  { iso: "CL", nameAr: "تشيلي", nameEn: "Chile", callingCode: "+56" },
  { iso: "CN", nameAr: "الصين", nameEn: "China", callingCode: "+86" },
  { iso: "CO", nameAr: "كولومبيا", nameEn: "Colombia", callingCode: "+57" },
  { iso: "KM", nameAr: "جزر القمر", nameEn: "Comoros", callingCode: "+269" },
  { iso: "CG", nameAr: "الكونغو", nameEn: "Republic of the Congo", callingCode: "+242" },
  { iso: "CD", nameAr: "الكونغو الديمقراطية", nameEn: "DR Congo", callingCode: "+243" },
  { iso: "CR", nameAr: "كوستاريكا", nameEn: "Costa Rica", callingCode: "+506" },
  { iso: "HR", nameAr: "كرواتيا", nameEn: "Croatia", callingCode: "+385" },
  { iso: "CU", nameAr: "كوبا", nameEn: "Cuba", callingCode: "+53" },
  { iso: "CY", nameAr: "قبرص", nameEn: "Cyprus", callingCode: "+357" },
  { iso: "CZ", nameAr: "التشيك", nameEn: "Czech Republic", callingCode: "+420" },
  { iso: "DK", nameAr: "الدنمارك", nameEn: "Denmark", callingCode: "+45" },
  { iso: "DJ", nameAr: "جيبوتي", nameEn: "Djibouti", callingCode: "+253" },
  { iso: "DM", nameAr: "دومينيكا", nameEn: "Dominica", callingCode: "+1-767" },
  { iso: "DO", nameAr: "جمهورية الدومينيكان", nameEn: "Dominican Republic", callingCode: "+1-809" },
  { iso: "EC", nameAr: "الإكوادور", nameEn: "Ecuador", callingCode: "+593" },
  { iso: "EG", nameAr: "مصر", nameEn: "Egypt", callingCode: "+20" },
  { iso: "SV", nameAr: "السلفادور", nameEn: "El Salvador", callingCode: "+503" },
  { iso: "GQ", nameAr: "غينيا الاستوائية", nameEn: "Equatorial Guinea", callingCode: "+240" },
  { iso: "ER", nameAr: "إريتريا", nameEn: "Eritrea", callingCode: "+291" },
  { iso: "EE", nameAr: "إستونيا", nameEn: "Estonia", callingCode: "+372" },
  { iso: "SZ", nameAr: "إيسواتيني", nameEn: "Eswatini", callingCode: "+268" },
  { iso: "ET", nameAr: "إثيوبيا", nameEn: "Ethiopia", callingCode: "+251" },
  { iso: "FJ", nameAr: "فيجي", nameEn: "Fiji", callingCode: "+679" },
  { iso: "FI", nameAr: "فنلندا", nameEn: "Finland", callingCode: "+358" },
  { iso: "FR", nameAr: "فرنسا", nameEn: "France", callingCode: "+33" },
  { iso: "GA", nameAr: "الغابون", nameEn: "Gabon", callingCode: "+241" },
  { iso: "GM", nameAr: "غامبيا", nameEn: "Gambia", callingCode: "+220" },
  { iso: "GE", nameAr: "جورجيا", nameEn: "Georgia", callingCode: "+995" },
  { iso: "DE", nameAr: "ألمانيا", nameEn: "Germany", callingCode: "+49" },
  { iso: "GH", nameAr: "غانا", nameEn: "Ghana", callingCode: "+233" },
  { iso: "GR", nameAr: "اليونان", nameEn: "Greece", callingCode: "+30" },
  { iso: "GD", nameAr: "غرينادا", nameEn: "Grenada", callingCode: "+1-473" },
  { iso: "GT", nameAr: "غواتيمالا", nameEn: "Guatemala", callingCode: "+502" },
  { iso: "GN", nameAr: "غينيا", nameEn: "Guinea", callingCode: "+224" },
  { iso: "GW", nameAr: "غينيا بيساو", nameEn: "Guinea-Bissau", callingCode: "+245" },
  { iso: "GY", nameAr: "غيانا", nameEn: "Guyana", callingCode: "+592" },
  { iso: "HT", nameAr: "هايتي", nameEn: "Haiti", callingCode: "+509" },
  { iso: "HN", nameAr: "هندوراس", nameEn: "Honduras", callingCode: "+504" },
  { iso: "HU", nameAr: "المجر", nameEn: "Hungary", callingCode: "+36" },
  { iso: "IS", nameAr: "آيسلندا", nameEn: "Iceland", callingCode: "+354" },
  { iso: "IN", nameAr: "الهند", nameEn: "India", callingCode: "+91" },
  { iso: "ID", nameAr: "إندونيسيا", nameEn: "Indonesia", callingCode: "+62" },
  { iso: "IR", nameAr: "إيران", nameEn: "Iran", callingCode: "+98" },
  { iso: "IQ", nameAr: "العراق", nameEn: "Iraq", callingCode: "+964" },
  { iso: "IE", nameAr: "أيرلندا", nameEn: "Ireland", callingCode: "+353" },
  { iso: "IL", nameAr: "إسرائيل", nameEn: "Israel", callingCode: "+972" },
  { iso: "IT", nameAr: "إيطاليا", nameEn: "Italy", callingCode: "+39" },
  { iso: "CI", nameAr: "ساحل العاج", nameEn: "Ivory Coast", callingCode: "+225" },
  { iso: "JM", nameAr: "جامايكا", nameEn: "Jamaica", callingCode: "+1-876" },
  { iso: "JP", nameAr: "اليابان", nameEn: "Japan", callingCode: "+81" },
  { iso: "JO", nameAr: "الأردن", nameEn: "Jordan", callingCode: "+962" },
  { iso: "KZ", nameAr: "كازاخستان", nameEn: "Kazakhstan", callingCode: "+7" },
  { iso: "KE", nameAr: "كينيا", nameEn: "Kenya", callingCode: "+254" },
  { iso: "KI", nameAr: "كيريباتي", nameEn: "Kiribati", callingCode: "+686" },
  { iso: "KP", nameAr: "كوريا الشمالية", nameEn: "North Korea", callingCode: "+850" },
  { iso: "KR", nameAr: "كوريا الجنوبية", nameEn: "South Korea", callingCode: "+82" },
  { iso: "KW", nameAr: "الكويت", nameEn: "Kuwait", callingCode: "+965" },
  { iso: "KG", nameAr: "قيرغيزستان", nameEn: "Kyrgyzstan", callingCode: "+996" },
  { iso: "LA", nameAr: "لاوس", nameEn: "Laos", callingCode: "+856" },
  { iso: "LV", nameAr: "لاتفيا", nameEn: "Latvia", callingCode: "+371" },
  { iso: "LB", nameAr: "لبنان", nameEn: "Lebanon", callingCode: "+961" },
  { iso: "LS", nameAr: "ليسوتو", nameEn: "Lesotho", callingCode: "+266" },
  { iso: "LR", nameAr: "ليبيريا", nameEn: "Liberia", callingCode: "+231" },
  { iso: "LY", nameAr: "ليبيا", nameEn: "Libya", callingCode: "+218" },
  { iso: "LI", nameAr: "ليختنشتاين", nameEn: "Liechtenstein", callingCode: "+423" },
  { iso: "LT", nameAr: "ليتوانيا", nameEn: "Lithuania", callingCode: "+370" },
  { iso: "LU", nameAr: "لوكسمبورغ", nameEn: "Luxembourg", callingCode: "+352" },
  { iso: "MG", nameAr: "مدغشقر", nameEn: "Madagascar", callingCode: "+261" },
  { iso: "MW", nameAr: "مالاوي", nameEn: "Malawi", callingCode: "+265" },
  { iso: "MY", nameAr: "ماليزيا", nameEn: "Malaysia", callingCode: "+60" },
  { iso: "MV", nameAr: "المالديف", nameEn: "Maldives", callingCode: "+960" },
  { iso: "ML", nameAr: "مالي", nameEn: "Mali", callingCode: "+223" },
  { iso: "MT", nameAr: "مالطا", nameEn: "Malta", callingCode: "+356" },
  { iso: "MH", nameAr: "جزر مارشال", nameEn: "Marshall Islands", callingCode: "+692" },
  { iso: "MR", nameAr: "موريتانيا", nameEn: "Mauritania", callingCode: "+222" },
  { iso: "MU", nameAr: "موريشيوس", nameEn: "Mauritius", callingCode: "+230" },
  { iso: "MX", nameAr: "المكسيك", nameEn: "Mexico", callingCode: "+52" },
  { iso: "FM", nameAr: "ميكرونيسيا", nameEn: "Micronesia", callingCode: "+691" },
  { iso: "MD", nameAr: "مولدوفا", nameEn: "Moldova", callingCode: "+373" },
  { iso: "MC", nameAr: "موناكو", nameEn: "Monaco", callingCode: "+377" },
  { iso: "MN", nameAr: "منغوليا", nameEn: "Mongolia", callingCode: "+976" },
  { iso: "ME", nameAr: "الجبل الأسود", nameEn: "Montenegro", callingCode: "+382" },
  { iso: "MA", nameAr: "المغرب", nameEn: "Morocco", callingCode: "+212" },
  { iso: "MZ", nameAr: "موزمبيق", nameEn: "Mozambique", callingCode: "+258" },
  { iso: "MM", nameAr: "ميانمار", nameEn: "Myanmar", callingCode: "+95" },
  { iso: "NA", nameAr: "ناميبيا", nameEn: "Namibia", callingCode: "+264" },
  { iso: "NR", nameAr: "ناورو", nameEn: "Nauru", callingCode: "+674" },
  { iso: "NP", nameAr: "نيبال", nameEn: "Nepal", callingCode: "+977" },
  { iso: "NL", nameAr: "هولندا", nameEn: "Netherlands", callingCode: "+31" },
  { iso: "NZ", nameAr: "نيوزيلندا", nameEn: "New Zealand", callingCode: "+64" },
  { iso: "NI", nameAr: "نيكاراغوا", nameEn: "Nicaragua", callingCode: "+505" },
  { iso: "NE", nameAr: "النيجر", nameEn: "Niger", callingCode: "+227" },
  { iso: "NG", nameAr: "نيجيريا", nameEn: "Nigeria", callingCode: "+234" },
  { iso: "MK", nameAr: "شمال مقدونيا", nameEn: "North Macedonia", callingCode: "+389" },
  { iso: "NO", nameAr: "النرويج", nameEn: "Norway", callingCode: "+47" },
  { iso: "OM", nameAr: "عُمان", nameEn: "Oman", callingCode: "+968" },
  { iso: "PK", nameAr: "باكستان", nameEn: "Pakistan", callingCode: "+92" },
  { iso: "PW", nameAr: "بالاو", nameEn: "Palau", callingCode: "+680" },
  { iso: "PS", nameAr: "فلسطين", nameEn: "Palestine", callingCode: "+970" },
  { iso: "PA", nameAr: "بنما", nameEn: "Panama", callingCode: "+507" },
  { iso: "PG", nameAr: "بابوا غينيا الجديدة", nameEn: "Papua New Guinea", callingCode: "+675" },
  { iso: "PY", nameAr: "باراغواي", nameEn: "Paraguay", callingCode: "+595" },
  { iso: "PE", nameAr: "بيرو", nameEn: "Peru", callingCode: "+51" },
  { iso: "PH", nameAr: "الفلبين", nameEn: "Philippines", callingCode: "+63" },
  { iso: "PL", nameAr: "بولندا", nameEn: "Poland", callingCode: "+48" },
  { iso: "PT", nameAr: "البرتغال", nameEn: "Portugal", callingCode: "+351" },
  { iso: "QA", nameAr: "قطر", nameEn: "Qatar", callingCode: "+974" },
  { iso: "RO", nameAr: "رومانيا", nameEn: "Romania", callingCode: "+40" },
  { iso: "RU", nameAr: "روسيا", nameEn: "Russia", callingCode: "+7" },
  { iso: "RW", nameAr: "رواندا", nameEn: "Rwanda", callingCode: "+250" },
  { iso: "KN", nameAr: "سان كيتس ونيفيس", nameEn: "Saint Kitts and Nevis", callingCode: "+1-869" },
  { iso: "LC", nameAr: "سانت لوسيا", nameEn: "Saint Lucia", callingCode: "+1-758" },
  { iso: "VC", nameAr: "سان فينسنت والغرينادين", nameEn: "Saint Vincent and the Grenadines", callingCode: "+1-784" },
  { iso: "WS", nameAr: "ساموا", nameEn: "Samoa", callingCode: "+685" },
  { iso: "SM", nameAr: "سان مارينو", nameEn: "San Marino", callingCode: "+378" },
  { iso: "ST", nameAr: "ساو تومي وبرينسيب", nameEn: "Sao Tome and Principe", callingCode: "+239" },
  { iso: "SA", nameAr: "السعودية", nameEn: "Saudi Arabia", callingCode: "+966" },
  { iso: "SN", nameAr: "السنغال", nameEn: "Senegal", callingCode: "+221" },
  { iso: "RS", nameAr: "صربيا", nameEn: "Serbia", callingCode: "+381" },
  { iso: "SC", nameAr: "سيشل", nameEn: "Seychelles", callingCode: "+248" },
  { iso: "SL", nameAr: "سيراليون", nameEn: "Sierra Leone", callingCode: "+232" },
  { iso: "SG", nameAr: "سنغافورة", nameEn: "Singapore", callingCode: "+65" },
  { iso: "SK", nameAr: "سلوفاكيا", nameEn: "Slovakia", callingCode: "+421" },
  { iso: "SI", nameAr: "سلوفينيا", nameEn: "Slovenia", callingCode: "+386" },
  { iso: "SB", nameAr: "جزر سليمان", nameEn: "Solomon Islands", callingCode: "+677" },
  { iso: "SO", nameAr: "الصومال", nameEn: "Somalia", callingCode: "+252" },
  { iso: "ZA", nameAr: "جنوب أفريقيا", nameEn: "South Africa", callingCode: "+27" },
  { iso: "SS", nameAr: "جنوب السودان", nameEn: "South Sudan", callingCode: "+211" },
  { iso: "ES", nameAr: "إسبانيا", nameEn: "Spain", callingCode: "+34" },
  { iso: "LK", nameAr: "سريلانكا", nameEn: "Sri Lanka", callingCode: "+94" },
  { iso: "SD", nameAr: "السودان", nameEn: "Sudan", callingCode: "+249" },
  { iso: "SR", nameAr: "سورينام", nameEn: "Suriname", callingCode: "+597" },
  { iso: "SE", nameAr: "السويد", nameEn: "Sweden", callingCode: "+46" },
  { iso: "CH", nameAr: "سويسرا", nameEn: "Switzerland", callingCode: "+41" },
  { iso: "SY", nameAr: "سوريا", nameEn: "Syria", callingCode: "+963" },
  { iso: "TJ", nameAr: "طاجيكستان", nameEn: "Tajikistan", callingCode: "+992" },
  { iso: "TZ", nameAr: "تنزانيا", nameEn: "Tanzania", callingCode: "+255" },
  { iso: "TH", nameAr: "تايلاند", nameEn: "Thailand", callingCode: "+66" },
  { iso: "TL", nameAr: "تيمور الشرقية", nameEn: "Timor-Leste", callingCode: "+670" },
  { iso: "TG", nameAr: "توغو", nameEn: "Togo", callingCode: "+228" },
  { iso: "TO", nameAr: "تونغا", nameEn: "Tonga", callingCode: "+676" },
  { iso: "TT", nameAr: "ترينيداد وتوباغو", nameEn: "Trinidad and Tobago", callingCode: "+1-868" },
  { iso: "TN", nameAr: "تونس", nameEn: "Tunisia", callingCode: "+216" },
  { iso: "TR", nameAr: "تركيا", nameEn: "Turkey", callingCode: "+90" },
  { iso: "TM", nameAr: "تركمانستان", nameEn: "Turkmenistan", callingCode: "+993" },
  { iso: "TV", nameAr: "توفالو", nameEn: "Tuvalu", callingCode: "+688" },
  { iso: "UG", nameAr: "أوغندا", nameEn: "Uganda", callingCode: "+256" },
  { iso: "UA", nameAr: "أوكرانيا", nameEn: "Ukraine", callingCode: "+380" },
  { iso: "AE", nameAr: "الإمارات", nameEn: "United Arab Emirates", callingCode: "+971" },
  { iso: "GB", nameAr: "المملكة المتحدة", nameEn: "United Kingdom", callingCode: "+44" },
  { iso: "US", nameAr: "الولايات المتحدة", nameEn: "United States", callingCode: "+1" },
  { iso: "UY", nameAr: "أوروغواي", nameEn: "Uruguay", callingCode: "+598" },
  { iso: "UZ", nameAr: "أوزبكستان", nameEn: "Uzbekistan", callingCode: "+998" },
  { iso: "VU", nameAr: "فانواتو", nameEn: "Vanuatu", callingCode: "+678" },
  { iso: "VA", nameAr: "الفاتيكان", nameEn: "Vatican City", callingCode: "+379" },
  { iso: "VE", nameAr: "فنزويلا", nameEn: "Venezuela", callingCode: "+58" },
  { iso: "VN", nameAr: "فيتنام", nameEn: "Vietnam", callingCode: "+84" },
  { iso: "YE", nameAr: "اليمن", nameEn: "Yemen", callingCode: "+967" },
  { iso: "ZM", nameAr: "زامبيا", nameEn: "Zambia", callingCode: "+260" },
  { iso: "ZW", nameAr: "زيمبابوي", nameEn: "Zimbabwe", callingCode: "+263" },
];

const _countryMap = new Map(COUNTRIES.map((c) => [c.iso, c]));

export function getCountryByIso(iso: string): CountryEntry | undefined {
  return _countryMap.get(iso);
}
