export type CurrencyEntry = {
  code: string;
  symbol: string;
  nameAr: string;
  nameEn: string;
};

export const CURRENCIES: CurrencyEntry[] = [
  { code: "AED", symbol: "د.إ", nameAr: "درهم إماراتي", nameEn: "UAE Dirham" },
  { code: "AFN", symbol: "؋", nameAr: "أفغاني", nameEn: "Afghan Afghani" },
  { code: "ALL", symbol: "L", nameAr: "ليك ألباني", nameEn: "Albanian Lek" },
  { code: "AMD", symbol: "֏", nameAr: "درام أرميني", nameEn: "Armenian Dram" },
  { code: "ANG", symbol: "ƒ", nameAr: "غيلدر أنتيلا", nameEn: "Netherlands Antillean Guilder" },
  { code: "AOA", symbol: "Kz", nameAr: "كوانزا أنغولي", nameEn: "Angolan Kwanza" },
  { code: "ARS", symbol: "$", nameAr: "بيسو أرجنتيني", nameEn: "Argentine Peso" },
  { code: "AUD", symbol: "A$", nameAr: "دولار أسترالي", nameEn: "Australian Dollar" },
  { code: "AWG", symbol: "ƒ", nameAr: "غيلدر أروبي", nameEn: "Aruban Florin" },
  { code: "AZN", symbol: "₼", nameAr: "مانات أذربيجاني", nameEn: "Azerbaijani Manat" },
  { code: "BAM", symbol: "KM", nameAr: "مارك البوسنة", nameEn: "Bosnia-Herzegovina Mark" },
  { code: "BBD", symbol: "Bds$", nameAr: "دولار باربادوسي", nameEn: "Barbadian Dollar" },
  { code: "BDT", symbol: "৳", nameAr: "تاكا بنغالي", nameEn: "Bangladeshi Taka" },
  { code: "BGN", symbol: "лв", nameAr: "ليف بلغاري", nameEn: "Bulgarian Lev" },
  { code: "BHD", symbol: "د.ب", nameAr: "دينار بحريني", nameEn: "Bahraini Dinar" },
  { code: "BIF", symbol: "FBu", nameAr: "فرنك بوروندي", nameEn: "Burundian Franc" },
  { code: "BMD", symbol: "BD$", nameAr: "دولار برمودي", nameEn: "Bermudian Dollar" },
  { code: "BND", symbol: "B$", nameAr: "دولار بروناي", nameEn: "Brunei Dollar" },
  { code: "BOB", symbol: "Bs", nameAr: "بوليفيانو بوليفي", nameEn: "Bolivian Boliviano" },
  { code: "BRL", symbol: "R$", nameAr: "ريال برازيلي", nameEn: "Brazilian Real" },
  { code: "BSD", symbol: "B$", nameAr: "دولار باهامي", nameEn: "Bahamian Dollar" },
  { code: "BTN", symbol: "Nu.", nameAr: "نولتروم بوتاني", nameEn: "Bhutanese Ngultrum" },
  { code: "BWP", symbol: "P", nameAr: "بولا بوتسواني", nameEn: "Botswana Pula" },
  { code: "BYN", symbol: "Br", nameAr: "روبل بيلاروسي", nameEn: "Belarusian Ruble" },
  { code: "BZD", symbol: "BZ$", nameAr: "دولار بليزي", nameEn: "Belize Dollar" },
  { code: "CAD", symbol: "CA$", nameAr: "دولار كندي", nameEn: "Canadian Dollar" },
  { code: "CDF", symbol: "FC", nameAr: "فرنك كونغولي", nameEn: "Congolese Franc" },
  { code: "CHF", symbol: "CHF", nameAr: "فرنك سويسري", nameEn: "Swiss Franc" },
  { code: "CLP", symbol: "CL$", nameAr: "بيسو تشيلي", nameEn: "Chilean Peso" },
  { code: "CNY", symbol: "¥", nameAr: "يوان صيني", nameEn: "Chinese Yuan" },
  { code: "COP", symbol: "CO$", nameAr: "بيسو كولومبي", nameEn: "Colombian Peso" },
  { code: "CRC", symbol: "₡", nameAr: "كولون كوستاريكي", nameEn: "Costa Rican Colon" },
  { code: "CUP", symbol: "$MN", nameAr: "بيسو كوبي", nameEn: "Cuban Peso" },
  { code: "CVE", symbol: "$", nameAr: "إسكودو الرأس الأخضر", nameEn: "Cape Verdean Escudo" },
  { code: "CZK", symbol: "Kč", nameAr: "كرونة تشيكية", nameEn: "Czech Koruna" },
  { code: "DJF", symbol: "Fdj", nameAr: "فرنك جيبوتي", nameEn: "Djiboutian Franc" },
  { code: "DKK", symbol: "kr", nameAr: "كرونة دنماركية", nameEn: "Danish Krone" },
  { code: "DOP", symbol: "RD$", nameAr: "بيسو دومينيكاني", nameEn: "Dominican Peso" },
  { code: "DZD", symbol: "د.ج", nameAr: "دينار جزائري", nameEn: "Algerian Dinar" },
  { code: "EGP", symbol: "ج.م", nameAr: "جنيه مصري", nameEn: "Egyptian Pound" },
  { code: "ERN", symbol: "Nfk", nameAr: "ناكفا إريتري", nameEn: "Eritrean Nakfa" },
  { code: "ETB", symbol: "Br", nameAr: "بير إثيوبي", nameEn: "Ethiopian Birr" },
  { code: "EUR", symbol: "€", nameAr: "يورو", nameEn: "Euro" },
  { code: "FJD", symbol: "FJ$", nameAr: "دولار فيجي", nameEn: "Fijian Dollar" },
  { code: "FKP", symbol: "£", nameAr: "جنيه جزر فوكلاند", nameEn: "Falkland Islands Pound" },
  { code: "GBP", symbol: "£", nameAr: "جنيه إسترليني", nameEn: "British Pound Sterling" },
  { code: "GEL", symbol: "₾", nameAr: "لاري جورجي", nameEn: "Georgian Lari" },
  { code: "GHS", symbol: "GH₵", nameAr: "سيدي غاني", nameEn: "Ghanaian Cedi" },
  { code: "GIP", symbol: "£", nameAr: "جنيه جبل طارق", nameEn: "Gibraltar Pound" },
  { code: "GMD", symbol: "D", nameAr: "دالاسي غامبي", nameEn: "Gambian Dalasi" },
  { code: "GNF", symbol: "FG", nameAr: "فرنك غيني", nameEn: "Guinean Franc" },
  { code: "GTQ", symbol: "Q", nameAr: "كيتزال غواتيمالي", nameEn: "Guatemalan Quetzal" },
  { code: "GYD", symbol: "G$", nameAr: "دولار غياني", nameEn: "Guyanaese Dollar" },
  { code: "HKD", symbol: "HK$", nameAr: "دولار هونغ كونغ", nameEn: "Hong Kong Dollar" },
  { code: "HNL", symbol: "L", nameAr: "ليمبيرا هندوراسية", nameEn: "Honduran Lempira" },
  { code: "HRK", symbol: "kn", nameAr: "كونا كرواتية", nameEn: "Croatian Kuna" },
  { code: "HTG", symbol: "G", nameAr: "غورد هايتي", nameEn: "Haitian Gourde" },
  { code: "HUF", symbol: "Ft", nameAr: "فورنت مجري", nameEn: "Hungarian Forint" },
  { code: "IDR", symbol: "Rp", nameAr: "روبية إندونيسية", nameEn: "Indonesian Rupiah" },
  { code: "ILS", symbol: "₪", nameAr: "شيكل إسرائيلي", nameEn: "Israeli New Shekel" },
  { code: "INR", symbol: "₹", nameAr: "روبية هندية", nameEn: "Indian Rupee" },
  { code: "IQD", symbol: "ع.د", nameAr: "دينار عراقي", nameEn: "Iraqi Dinar" },
  { code: "IRR", symbol: "﷼", nameAr: "ريال إيراني", nameEn: "Iranian Rial" },
  { code: "ISK", symbol: "kr", nameAr: "كرونة آيسلندية", nameEn: "Icelandic Krona" },
  { code: "JMD", symbol: "J$", nameAr: "دولار جامايكي", nameEn: "Jamaican Dollar" },
  { code: "JOD", symbol: "د.ا", nameAr: "دينار أردني", nameEn: "Jordanian Dinar" },
  { code: "JPY", symbol: "¥", nameAr: "ين ياباني", nameEn: "Japanese Yen" },
  { code: "KES", symbol: "KSh", nameAr: "شيلينغ كيني", nameEn: "Kenyan Shilling" },
  { code: "KGS", symbol: "с", nameAr: "سوم قيرغيزستاني", nameEn: "Kyrgyzstani Som" },
  { code: "KHR", symbol: "៛", nameAr: "رييل كمبودي", nameEn: "Cambodian Riel" },
  { code: "KMF", symbol: "CF", nameAr: "فرنك جزر القمر", nameEn: "Comorian Franc" },
  { code: "KPW", symbol: "₩", nameAr: "وون كوري شمالي", nameEn: "North Korean Won" },
  { code: "KRW", symbol: "₩", nameAr: "وون كوري جنوبي", nameEn: "South Korean Won" },
  { code: "KWD", symbol: "د.ك", nameAr: "دينار كويتي", nameEn: "Kuwaiti Dinar" },
  { code: "KYD", symbol: "CI$", nameAr: "دولار جزر كايمان", nameEn: "Cayman Islands Dollar" },
  { code: "KZT", symbol: "₸", nameAr: "تينغ كازاخستاني", nameEn: "Kazakhstani Tenge" },
  { code: "LAK", symbol: "₭", nameAr: "كيب لاوي", nameEn: "Laotian Kip" },
  { code: "LBP", symbol: "ل.ل", nameAr: "جنيه لبناني", nameEn: "Lebanese Pound" },
  { code: "LKR", symbol: "Rs", nameAr: "روبية سريلانكية", nameEn: "Sri Lankan Rupee" },
  { code: "LRD", symbol: "L$", nameAr: "دولار ليبيري", nameEn: "Liberian Dollar" },
  { code: "LSL", symbol: "M", nameAr: "لوتي ليسوتو", nameEn: "Lesotho Loti" },
  { code: "LYD", symbol: "ل.د", nameAr: "دينار ليبي", nameEn: "Libyan Dinar" },
  { code: "MAD", symbol: "د.م.", nameAr: "درهم مغربي", nameEn: "Moroccan Dirham" },
  { code: "MDL", symbol: "L", nameAr: "ليو مولدوفي", nameEn: "Moldovan Leu" },
  { code: "MGA", symbol: "Ar", nameAr: "أرياري مدغشقري", nameEn: "Malagasy Ariary" },
  { code: "MKD", symbol: "ден", nameAr: "دينار مقدوني", nameEn: "Macedonian Denar" },
  { code: "MMK", symbol: "K", nameAr: "كيات ميانماري", nameEn: "Myanmar Kyat" },
  { code: "MNT", symbol: "₮", nameAr: "توغريك منغولي", nameEn: "Mongolian Tugrik" },
  { code: "MOP", symbol: "MOP$", nameAr: "باتاكا ماكاوي", nameEn: "Macanese Pataca" },
  { code: "MRU", symbol: "UM", nameAr: "أوقية موريتانية", nameEn: "Mauritanian Ouguiya" },
  { code: "MUR", symbol: "₨", nameAr: "روبية موريشيوسية", nameEn: "Mauritian Rupee" },
  { code: "MVR", symbol: "Rf", nameAr: "روفية مالديفية", nameEn: "Maldivian Rufiyaa" },
  { code: "MWK", symbol: "MK", nameAr: "كواشا ملاوية", nameEn: "Malawian Kwacha" },
  { code: "MXN", symbol: "Mex$", nameAr: "بيسو مكسيكي", nameEn: "Mexican Peso" },
  { code: "MYR", symbol: "RM", nameAr: "رينغيت ماليزي", nameEn: "Malaysian Ringgit" },
  { code: "MZN", symbol: "MT", nameAr: "ميتيكال mozambican", nameEn: "Mozambican Metical" },
  { code: "NAD", symbol: "N$", nameAr: "دولار ناميبي", nameEn: "Namibian Dollar" },
  { code: "NGN", symbol: "₦", nameAr: "نايرة نيجيرية", nameEn: "Nigerian Naira" },
  { code: "NIO", symbol: "C$", nameAr: "كوردوبا نيكاراغوي", nameEn: "Nicaraguan Cordoba" },
  { code: "NOK", symbol: "kr", nameAr: "كرونة نرويجية", nameEn: "Norwegian Krone" },
  { code: "NPR", symbol: "₨", nameAr: "روبية نيبالية", nameEn: "Nepalese Rupee" },
  { code: "NZD", symbol: "NZ$", nameAr: "دولار نيوزيلندي", nameEn: "New Zealand Dollar" },
  { code: "OMR", symbol: "ر.ع.", nameAr: "ريال عُماني", nameEn: "Omani Rial" },
  { code: "PAB", symbol: "B/.", nameAr: "بالبوا بنمي", nameEn: "Panamanian Balboa" },
  { code: "PEN", symbol: "S/", nameAr: "سول بيروفي", nameEn: "Peruvian Sol" },
  { code: "PGK", symbol: "K", nameAr: "كينا بابوا غينية", nameEn: "Papua New Guinean Kina" },
  { code: "PHP", symbol: "₱", nameAr: "بيسو فلبيني", nameEn: "Philippine Peso" },
  { code: "PKR", symbol: "₨", nameAr: "روبية باكستانية", nameEn: "Pakistani Rupee" },
  { code: "PLN", symbol: "zł", nameAr: "زلوتي بولندي", nameEn: "Polish Zloty" },
  { code: "PYG", symbol: "₲", nameAr: "غواراني باراغواي", nameEn: "Paraguayan Guarani" },
  { code: "QAR", symbol: "ر.ق", nameAr: "ريال قطري", nameEn: "Qatari Rial" },
  { code: "RON", symbol: "lei", nameAr: "ليو روماني", nameEn: "Romanian Leu" },
  { code: "RSD", symbol: "дин", nameAr: "دينار صربي", nameEn: "Serbian Dinar" },
  { code: "RUB", symbol: "₽", nameAr: "روبل روسي", nameEn: "Russian Ruble" },
  { code: "RWF", symbol: "FRw", nameAr: "فرنك رواندي", nameEn: "Rwandan Franc" },
  { code: "SAR", symbol: "ر.س", nameAr: "ريال سعودي", nameEn: "Saudi Riyal" },
  { code: "SBD", symbol: "SI$", nameAr: "دولار جزر سليمان", nameEn: "Solomon Islands Dollar" },
  { code: "SCR", symbol: "₨", nameAr: "روبية سيشلية", nameEn: "Seychellois Rupee" },
  { code: "SDG", symbol: "ج.س.", nameAr: "جنيه سوداني", nameEn: "Sudanese Pound" },
  { code: "SEK", symbol: "kr", nameAr: "كرونة سويدية", nameEn: "Swedish Krona" },
  { code: "SGD", symbol: "S$", nameAr: "دولار سنغافوري", nameEn: "Singapore Dollar" },
  { code: "SHP", symbol: "£", nameAr: "جنيه سانت هيلينا", nameEn: "Saint Helena Pound" },
  { code: "SLE", symbol: "Le", nameAr: "ليون سيراليوني", nameEn: "Sierra Leonean Leone" },
  { code: "SOS", symbol: "Sh", nameAr: "شيلينغ صومالي", nameEn: "Somali Shilling" },
  { code: "SRD", symbol: "$", nameAr: "دولار سورينامي", nameEn: "Surinamese Dollar" },
  { code: "SSP", symbol: "£", nameAr: "جنيه جنوب سوداني", nameEn: "South Sudanese Pound" },
  { code: "STN", symbol: "Db", nameAr: "دوبرا ساو تومية", nameEn: "Sao Tomean Dobra" },
  { code: "SVC", symbol: "$", nameAr: "كولون سلفادوري", nameEn: "Salvadoran Colon" },
  { code: "SYP", symbol: "ل.س", nameAr: "ليرة سورية", nameEn: "Syrian Pound" },
  { code: "SZL", symbol: "E", nameAr: "ليلانغيني سوازي", nameEn: "Eswatini Lilangeni" },
  { code: "THB", symbol: "฿", nameAr: "بات تايلاندي", nameEn: "Thai Baht" },
  { code: "TJS", symbol: "SM", nameAr: "سوموني طاجيكي", nameEn: "Tajikistani Somoni" },
  { code: "TMT", symbol: "m", nameAr: "مانات تركمانستاني", nameEn: "Turkmenistani Manat" },
  { code: "TND", symbol: "د.ت", nameAr: "دينار تونسي", nameEn: "Tunisian Dinar" },
  { code: "TOP", symbol: "T$", nameAr: "بانغا تونغانية", nameEn: "Tongan Pa'anga" },
  { code: "TRY", symbol: "₺", nameAr: "ليرة تركية", nameEn: "Turkish Lira" },
  { code: "TTD", symbol: "TT$", nameAr: "دولار ترينيدادي", nameEn: "Trinidad and Tobago Dollar" },
  { code: "TWD", symbol: "NT$", nameAr: "دولار تايواني", nameEn: "New Taiwan Dollar" },
  { code: "TZS", symbol: "TSh", nameAr: "شيلينغ تنزاني", nameEn: "Tanzanian Shilling" },
  { code: "UAH", symbol: "₴", nameAr: "هريفنيا أوكرانية", nameEn: "Ukrainian Hryvnia" },
  { code: "UGX", symbol: "USh", nameAr: "شيلينغ أوغندي", nameEn: "Ugandan Shilling" },
  { code: "USD", symbol: "$", nameAr: "دولار أمريكي", nameEn: "US Dollar" },
  { code: "UYU", symbol: "$U", nameAr: "بيسو أوروغواي", nameEn: "Uruguayan Peso" },
  { code: "UZS", symbol: "сўм", nameAr: "سوم أوزبكي", nameEn: "Uzbekistani Som" },
  { code: "VES", symbol: "Bs.S", nameAr: "بوليفار فنزويلي", nameEn: "Venezuelan Bolivar" },
  { code: "VND", symbol: "₫", nameAr: "دونغ فيتنامي", nameEn: "Vietnamese Dong" },
  { code: "VUV", symbol: "VT", nameAr: "فاتو فانواتو", nameEn: "Vanuatu Vatu" },
  { code: "WST", symbol: "WS$", nameAr: "تالا ساموية", nameEn: "Samoan Tala" },
  { code: "XAF", symbol: "FCFA", nameAr: "فرنك وسط أفريقي", nameEn: "Central African CFA Franc" },
  { code: "XCD", symbol: "EC$", nameAr: "دولار شرق الكاريبي", nameEn: "East Caribbean Dollar" },
  { code: "XOF", symbol: "F", nameAr: "فرنك غرب أفريقي", nameEn: "West African CFA Franc" },
  { code: "XPF", symbol: "₣", nameAr: "فرنك شرق المحيط الهادئ", nameEn: "CFP Franc" },
  { code: "YER", symbol: "﷼", nameAr: "ريال يمني", nameEn: "Yemeni Rial" },
  { code: "ZAR", symbol: "R", nameAr: "راند جنوب أفريقي", nameEn: "South African Rand" },
  { code: "ZMW", symbol: "ZK", nameAr: "كواشا زامبية", nameEn: "Zambian Kwacha" },
  { code: "ZWL", symbol: "ZWL$", nameAr: "دولار زيمبابوي", nameEn: "Zimbabwean Dollar" },
];

const _currencyMap = new Map(CURRENCIES.map((c) => [c.code, c]));

export function getCurrencyByCode(code: string): CurrencyEntry | undefined {
  return _currencyMap.get(code);
}
