export type LibraryTemplateType = "meta" | "quick_reply";
export type MetaCategory = "MARKETING" | "UTILITY" | "AUTHENTICATION";

export type Industry =
  | "ecommerce"
  | "food"
  | "health"
  | "realestate"
  | "education"
  | "beauty"
  | "auto"
  | "finance"
  | "travel"
  | "general";

export const INDUSTRY_LABELS: Record<Industry, { en: string; ar: string; icon: string }> = {
  ecommerce:  { en: "E-commerce & Retail",  ar: "التجارة الإلكترونية", icon: "🛍️" },
  food:       { en: "Food & Restaurants",   ar: "المطاعم والأكل",      icon: "🍽️" },
  health:     { en: "Healthcare & Clinics", ar: "الصحة والعيادات",     icon: "🏥" },
  realestate: { en: "Real Estate",          ar: "العقارات",            icon: "🏠" },
  education:  { en: "Education & Training", ar: "التعليم والتدريب",    icon: "🎓" },
  beauty:     { en: "Beauty & Salons",      ar: "الجمال والصالونات",   icon: "💅" },
  auto:       { en: "Auto & Services",      ar: "السيارات والخدمات",   icon: "🚗" },
  finance:    { en: "Finance & Insurance",  ar: "المالية والتأمين",    icon: "💰" },
  travel:     { en: "Travel & Tourism",     ar: "السفر والسياحة",      icon: "✈️" },
  general:    { en: "General / Other",      ar: "عام",                 icon: "⚙️" },
};

export type LibraryTemplate = {
  id: string;
  title: string;
  type: LibraryTemplateType;
  category: string;
  language: "ar" | "en";
  body: string;
  variables: string[];
  metaCategory?: MetaCategory;
  industries: Industry[];
};

export const LIBRARY_CATEGORIES: Record<LibraryTemplateType, string[]> = {
  meta: [
    "promotions",
    "orders",
    "appointments",
    "payments",
    "welcome",
    "feedback",
    "alerts",
    "reengagement",
  ],
  quick_reply: [
    "greetings",
    "complaints",
    "support",
    "closing",
    "handoff",
    "out_of_hours",
  ],
};

export const CATEGORY_LABELS: Record<string, { en: string; ar: string; icon: string }> = {
  promotions:   { en: "Promotions & Offers",    ar: "العروض والخصومات",    icon: "📢" },
  orders:       { en: "Order Updates",           ar: "تحديثات الطلبات",     icon: "📦" },
  appointments: { en: "Appointments",            ar: "المواعيد",            icon: "📅" },
  payments:     { en: "Payments & Invoices",     ar: "المدفوعات والفواتير", icon: "💳" },
  welcome:      { en: "Welcome & Onboarding",    ar: "الترحيب",             icon: "👋" },
  feedback:     { en: "Feedback & CSAT",         ar: "التقييم",             icon: "⭐" },
  alerts:       { en: "Alerts & Notifications",  ar: "التنبيهات",           icon: "🔔" },
  reengagement: { en: "Re-engagement",           ar: "إعادة التواصل",       icon: "🔄" },
  greetings:    { en: "Greetings",               ar: "التحيات",             icon: "🤝" },
  complaints:   { en: "Complaints & Escalation", ar: "الشكاوى والتصعيد",   icon: "😟" },
  support:      { en: "Technical Support",       ar: "الدعم الفني",         icon: "🛠️" },
  closing:      { en: "Closing & Resolution",    ar: "الإغلاق",             icon: "✅" },
  handoff:      { en: "Handoff & Transfer",      ar: "التحويل",             icon: "🔀" },
  out_of_hours: { en: "Out of Hours",            ar: "خارج أوقات العمل",    icon: "🌙" },
};

function vars(body: string): string[] {
  const matches = body.matchAll(/\{\{(\w+)\}\}/g);
  return [...new Set([...matches].map((m) => m[1].toLowerCase()))];
}

const RAW: Omit<LibraryTemplate, "variables">[] = [
  // ── META: PROMOTIONS ──────────────────────────────────────────────────────
  {
    id: "promo-flash-sale-ar",
    title: "Flash Sale",
    type: "meta",
    category: "promotions",
    language: "ar",
    body: "🎉 خصم {{discount}}% على جميع المنتجات! العرض ساري لمدة {{hours}} ساعة فقط. سارع بالطلب الآن!",
    metaCategory: "MARKETING",
    industries: ["ecommerce", "food", "beauty"],
  },
  {
    id: "promo-flash-sale-en",
    title: "Flash Sale",
    type: "meta",
    category: "promotions",
    language: "en",
    body: "🎉 {{discount}}% OFF everything! Offer valid for {{hours}} hours only. Order now!",
    metaCategory: "MARKETING",
    industries: ["ecommerce", "food", "beauty"],
  },
  {
    id: "promo-seasonal-ar",
    title: "Seasonal Offer",
    type: "meta",
    category: "promotions",
    language: "ar",
    body: "مرحباً {{name}}! بمناسبة {{occasion}}، نقدم لك خصم {{discount}}% باستخدام كود {{code}}. استمتع بالتسوق! 🛍️",
    metaCategory: "MARKETING",
    industries: ["ecommerce", "food", "beauty", "travel"],
  },
  {
    id: "promo-seasonal-en",
    title: "Seasonal Offer",
    type: "meta",
    category: "promotions",
    language: "en",
    body: "Hi {{name}}! To celebrate {{occasion}}, enjoy {{discount}}% off with code {{code}}. Happy shopping! 🛍️",
    metaCategory: "MARKETING",
    industries: ["ecommerce", "food", "beauty", "travel"],
  },
  {
    id: "promo-new-arrival-ar",
    title: "New Arrival",
    type: "meta",
    category: "promotions",
    language: "ar",
    body: "وصل الجديد! 🛍️ تشكيلة {{product}} متاحة الآن. تسوّق قبل نفاد الكمية.",
    metaCategory: "MARKETING",
    industries: ["ecommerce"],
  },
  {
    id: "promo-new-arrival-en",
    title: "New Arrival",
    type: "meta",
    category: "promotions",
    language: "en",
    body: "New arrivals are here! 🛍️ The {{product}} collection is now available. Shop before it sells out.",
    metaCategory: "MARKETING",
    industries: ["ecommerce"],
  },

  // ── META: ORDERS ──────────────────────────────────────────────────────────
  {
    id: "order-confirmed-ar",
    title: "Order Confirmed",
    type: "meta",
    category: "orders",
    language: "ar",
    body: "✅ تم تأكيد طلبك رقم {{order_id}}. سنبدأ التجهيز فوراً وسنخطرك عند الشحن.",
    metaCategory: "UTILITY",
    industries: ["ecommerce", "food"],
  },
  {
    id: "order-confirmed-en",
    title: "Order Confirmed",
    type: "meta",
    category: "orders",
    language: "en",
    body: "✅ Order #{{order_id}} confirmed! We'll start processing right away and notify you when shipped.",
    metaCategory: "UTILITY",
    industries: ["ecommerce", "food"],
  },
  {
    id: "order-shipped-ar",
    title: "Order Shipped",
    type: "meta",
    category: "orders",
    language: "ar",
    body: "📦 طلبك رقم {{order_id}} اتشحن! رقم التتبع: {{tracking_number}}. هيوصلك خلال {{days}} أيام.",
    metaCategory: "UTILITY",
    industries: ["ecommerce"],
  },
  {
    id: "order-shipped-en",
    title: "Order Shipped",
    type: "meta",
    category: "orders",
    language: "en",
    body: "📦 Order #{{order_id}} is on its way! Tracking: {{tracking_number}}. Expected in {{days}} days.",
    metaCategory: "UTILITY",
    industries: ["ecommerce"],
  },
  {
    id: "order-delivered-ar",
    title: "Order Delivered",
    type: "meta",
    category: "orders",
    language: "ar",
    body: "🎉 طلبك رقم {{order_id}} اتوصّل! نتمنى تكون راضي. لو في أي مشكلة تواصل معنا.",
    metaCategory: "UTILITY",
    industries: ["ecommerce", "food"],
  },
  {
    id: "order-delivered-en",
    title: "Order Delivered",
    type: "meta",
    category: "orders",
    language: "en",
    body: "🎉 Order #{{order_id}} has been delivered! Hope you love it. Reach out if anything needs attention.",
    metaCategory: "UTILITY",
    industries: ["ecommerce", "food"],
  },

  // ── META: APPOINTMENTS ────────────────────────────────────────────────────
  {
    id: "appt-confirmed-ar",
    title: "Appointment Confirmed",
    type: "meta",
    category: "appointments",
    language: "ar",
    body: "✅ تم تأكيد موعدك يوم {{date}} الساعة {{time}} في {{location}}. نراك قريباً!",
    metaCategory: "UTILITY",
    industries: ["health", "beauty", "auto", "education", "finance"],
  },
  {
    id: "appt-confirmed-en",
    title: "Appointment Confirmed",
    type: "meta",
    category: "appointments",
    language: "en",
    body: "✅ Appointment confirmed for {{date}} at {{time}} at {{location}}. See you soon!",
    metaCategory: "UTILITY",
    industries: ["health", "beauty", "auto", "education", "finance"],
  },
  {
    id: "appt-reminder-ar",
    title: "Appointment Reminder",
    type: "meta",
    category: "appointments",
    language: "ar",
    body: "⏰ تذكير: موعدك يوم {{date}} الساعة {{time}}. لو محتاج تعيد جدولة تواصل معنا مسبقاً.",
    metaCategory: "UTILITY",
    industries: ["health", "beauty", "auto", "education", "finance"],
  },
  {
    id: "appt-reminder-en",
    title: "Appointment Reminder",
    type: "meta",
    category: "appointments",
    language: "en",
    body: "⏰ Reminder: Your appointment is on {{date}} at {{time}}. Need to reschedule? Contact us in advance.",
    metaCategory: "UTILITY",
    industries: ["health", "beauty", "auto", "education", "finance"],
  },
  {
    id: "appt-cancelled-ar",
    title: "Appointment Cancelled",
    type: "meta",
    category: "appointments",
    language: "ar",
    body: "❌ تم إلغاء موعدك يوم {{date}}. تواصل معنا لحجز موعد جديد في أي وقت.",
    metaCategory: "UTILITY",
    industries: ["health", "beauty", "auto", "education", "finance"],
  },
  {
    id: "appt-cancelled-en",
    title: "Appointment Cancelled",
    type: "meta",
    category: "appointments",
    language: "en",
    body: "❌ Your appointment on {{date}} has been cancelled. Contact us anytime to book a new one.",
    metaCategory: "UTILITY",
    industries: ["health", "beauty", "auto", "education", "finance"],
  },

  // ── META: PAYMENTS ────────────────────────────────────────────────────────
  {
    id: "payment-received-ar",
    title: "Payment Received",
    type: "meta",
    category: "payments",
    language: "ar",
    body: "✅ استلمنا دفعتك بقيمة {{amount}} بتاريخ {{date}}. شكراً لثقتك بنا!",
    metaCategory: "UTILITY",
    industries: ["ecommerce", "realestate", "finance"],
  },
  {
    id: "payment-received-en",
    title: "Payment Received",
    type: "meta",
    category: "payments",
    language: "en",
    body: "✅ Payment of {{amount}} received on {{date}}. Thank you for your trust!",
    metaCategory: "UTILITY",
    industries: ["ecommerce", "realestate", "finance"],
  },
  {
    id: "payment-due-ar",
    title: "Payment Due",
    type: "meta",
    category: "payments",
    language: "ar",
    body: "📋 تذكير: الفاتورة رقم {{invoice_id}} بقيمة {{amount}} مستحقة بتاريخ {{due_date}}.",
    metaCategory: "UTILITY",
    industries: ["ecommerce", "realestate", "finance"],
  },
  {
    id: "payment-due-en",
    title: "Payment Due",
    type: "meta",
    category: "payments",
    language: "en",
    body: "📋 Reminder: Invoice #{{invoice_id}} for {{amount}} is due on {{due_date}}.",
    metaCategory: "UTILITY",
    industries: ["ecommerce", "realestate", "finance"],
  },
  {
    id: "payment-failed-ar",
    title: "Payment Failed",
    type: "meta",
    category: "payments",
    language: "ar",
    body: "⚠️ للأسف فشلت عملية الدفع رقم {{payment_id}}. تواصل معنا لحل المشكلة في أقرب وقت.",
    metaCategory: "UTILITY",
    industries: ["ecommerce", "realestate", "finance"],
  },
  {
    id: "payment-failed-en",
    title: "Payment Failed",
    type: "meta",
    category: "payments",
    language: "en",
    body: "⚠️ Payment #{{payment_id}} failed. Please contact us to resolve this as soon as possible.",
    metaCategory: "UTILITY",
    industries: ["ecommerce", "realestate", "finance"],
  },

  // ── META: WELCOME ─────────────────────────────────────────────────────────
  {
    id: "welcome-new-ar",
    title: "Welcome New Customer",
    type: "meta",
    category: "welcome",
    language: "ar",
    body: "أهلاً وسهلاً {{name}}! 🎉 يسعدنا انضمامك لعائلة {{business}}. فريقنا جاهز لمساعدتك في أي وقت.",
    metaCategory: "MARKETING",
    industries: ["general"],
  },
  {
    id: "welcome-new-en",
    title: "Welcome New Customer",
    type: "meta",
    category: "welcome",
    language: "en",
    body: "Welcome {{name}}! 🎉 We're thrilled to have you join {{business}}. Our team is ready to help anytime.",
    metaCategory: "MARKETING",
    industries: ["general"],
  },
  {
    id: "welcome-account-ar",
    title: "Account Created",
    type: "meta",
    category: "welcome",
    language: "ar",
    body: "تم إنشاء حسابك في {{business}} بنجاح! يمكنك الآن الاستمتاع بجميع خدماتنا.",
    metaCategory: "UTILITY",
    industries: ["general"],
  },
  {
    id: "welcome-account-en",
    title: "Account Created",
    type: "meta",
    category: "welcome",
    language: "en",
    body: "Your {{business}} account has been successfully created! You can now enjoy all our services.",
    metaCategory: "UTILITY",
    industries: ["general"],
  },

  // ── META: FEEDBACK ────────────────────────────────────────────────────────
  {
    id: "feedback-csat-ar",
    title: "CSAT Request",
    type: "meta",
    category: "feedback",
    language: "ar",
    body: "شكراً لتواصلك مع {{business}} 😊 كيف كانت تجربتك معنا؟ ردّك مهم جداً لتطوير خدمتنا.",
    metaCategory: "UTILITY",
    industries: ["general"],
  },
  {
    id: "feedback-csat-en",
    title: "CSAT Request",
    type: "meta",
    category: "feedback",
    language: "en",
    body: "Thanks for contacting {{business}} 😊 How was your experience? Your feedback helps us improve.",
    metaCategory: "UTILITY",
    industries: ["general"],
  },
  {
    id: "feedback-review-ar",
    title: "Review Request",
    type: "meta",
    category: "feedback",
    language: "ar",
    body: "عميلنا العزيز {{name}}، نتمنى تكون راضياً عن خدمتنا. شاركنا رأيك لنتحسن أكثر! 🌟",
    metaCategory: "MARKETING",
    industries: ["general"],
  },
  {
    id: "feedback-review-en",
    title: "Review Request",
    type: "meta",
    category: "feedback",
    language: "en",
    body: "Dear {{name}}, we hope you're satisfied with our service. Share your feedback to help us improve! 🌟",
    metaCategory: "MARKETING",
    industries: ["general"],
  },

  // ── META: ALERTS ──────────────────────────────────────────────────────────
  {
    id: "alert-account-ar",
    title: "Account Security Alert",
    type: "meta",
    category: "alerts",
    language: "ar",
    body: "⚠️ تم تسجيل دخول لحسابك في {{business}} من جهاز جديد بتاريخ {{date}}. لو مش أنت، تواصل معنا فوراً.",
    metaCategory: "UTILITY",
    industries: ["general", "finance"],
  },
  {
    id: "alert-account-en",
    title: "Account Security Alert",
    type: "meta",
    category: "alerts",
    language: "en",
    body: "⚠️ Your {{business}} account was accessed from a new device on {{date}}. If this wasn't you, contact us immediately.",
    metaCategory: "UTILITY",
    industries: ["general", "finance"],
  },
  {
    id: "alert-service-ar",
    title: "Service Update",
    type: "meta",
    category: "alerts",
    language: "ar",
    body: "📢 إشعار مهم من {{business}}: {{message}}. لأي استفسار تواصل معنا.",
    metaCategory: "UTILITY",
    industries: ["general"],
  },
  {
    id: "alert-service-en",
    title: "Service Update",
    type: "meta",
    category: "alerts",
    language: "en",
    body: "📢 Important update from {{business}}: {{message}}. Contact us for any questions.",
    metaCategory: "UTILITY",
    industries: ["general"],
  },

  // ── META: RE-ENGAGEMENT ───────────────────────────────────────────────────
  {
    id: "reengagement-winback-ar",
    title: "Win-Back",
    type: "meta",
    category: "reengagement",
    language: "ar",
    body: "مش شايفينك من زمان {{name}} 😢 عندنا عروض جديدة تناسبك. تواصل معنا وهنساعدك!",
    metaCategory: "MARKETING",
    industries: ["ecommerce", "food", "beauty"],
  },
  {
    id: "reengagement-winback-en",
    title: "Win-Back",
    type: "meta",
    category: "reengagement",
    language: "en",
    body: "We miss you {{name}} 😢 We have new offers just for you. Reach out and let us help!",
    metaCategory: "MARKETING",
    industries: ["ecommerce", "food", "beauty"],
  },
  {
    id: "reengagement-followup-ar",
    title: "Follow-Up",
    type: "meta",
    category: "reengagement",
    language: "ar",
    body: "هل كل شيء تمام؟ آخر تواصل كان منذ {{days}} أيام. فريقنا جاهز لو محتاج أي مساعدة.",
    metaCategory: "UTILITY",
    industries: ["general"],
  },
  {
    id: "reengagement-followup-en",
    title: "Follow-Up",
    type: "meta",
    category: "reengagement",
    language: "en",
    body: "Is everything okay? It's been {{days}} days since we last spoke. Our team is here if you need anything.",
    metaCategory: "UTILITY",
    industries: ["general"],
  },

  // ── QUICK-REPLY: GREETINGS ────────────────────────────────────────────────
  {
    id: "qr-greeting-opening-ar",
    title: "Opening Greeting",
    type: "quick_reply",
    category: "greetings",
    language: "ar",
    body: "أهلاً {{name}}! كيف أقدر أساعدك اليوم؟ 😊",
    industries: ["general"],
  },
  {
    id: "qr-greeting-opening-en",
    title: "Opening Greeting",
    type: "quick_reply",
    category: "greetings",
    language: "en",
    body: "Hi {{name}}! How can I help you today? 😊",
    industries: ["general"],
  },
  {
    id: "qr-greeting-formal-ar",
    title: "Formal Welcome",
    type: "quick_reply",
    category: "greetings",
    language: "ar",
    body: "السلام عليكم ورحمة الله، أهلاً بك في {{business}}. كيف يمكنني خدمتك؟",
    industries: ["general"],
  },
  {
    id: "qr-greeting-formal-en",
    title: "Formal Welcome",
    type: "quick_reply",
    category: "greetings",
    language: "en",
    body: "Hello and welcome to {{business}}. How may I assist you today?",
    industries: ["general"],
  },
  {
    id: "qr-greeting-returning-ar",
    title: "Returning Customer",
    type: "quick_reply",
    category: "greetings",
    language: "ar",
    body: "أهلاً {{name}}! سعيدين بعودتك. كيف نقدر نساعدك؟",
    industries: ["general"],
  },
  {
    id: "qr-greeting-returning-en",
    title: "Returning Customer",
    type: "quick_reply",
    category: "greetings",
    language: "en",
    body: "Welcome back {{name}}! Great to hear from you again. How can we help?",
    industries: ["general"],
  },

  // ── QUICK-REPLY: COMPLAINTS ───────────────────────────────────────────────
  {
    id: "qr-complaint-apology-ar",
    title: "Apology",
    type: "quick_reply",
    category: "complaints",
    language: "ar",
    body: "نعتذر جداً عن الإزعاج {{name}}. هنحل المشكلة دي فوراً ونضمن مش تتكرر.",
    industries: ["general"],
  },
  {
    id: "qr-complaint-apology-en",
    title: "Apology",
    type: "quick_reply",
    category: "complaints",
    language: "en",
    body: "We sincerely apologize for the inconvenience {{name}}. We'll resolve this right away and ensure it doesn't happen again.",
    industries: ["general"],
  },
  {
    id: "qr-complaint-escalation-ar",
    title: "Escalation Acknowledgment",
    type: "quick_reply",
    category: "complaints",
    language: "ar",
    body: "فهمت المشكلة {{name}}. هرفع الموضوع للقسم المختص وهيتواصل معك خلال {{hours}} ساعات.",
    industries: ["general"],
  },
  {
    id: "qr-complaint-escalation-en",
    title: "Escalation Acknowledgment",
    type: "quick_reply",
    category: "complaints",
    language: "en",
    body: "I understand your concern {{name}}. I'm escalating this to the relevant team and they'll contact you within {{hours}} hours.",
    industries: ["general"],
  },

  // ── QUICK-REPLY: SUPPORT ──────────────────────────────────────────────────
  {
    id: "qr-support-troubleshoot-ar",
    title: "Troubleshooting Steps",
    type: "quick_reply",
    category: "support",
    language: "ar",
    body: "جرب الخطوات دي لحل المشكلة:\n1️⃣ أعد تشغيل التطبيق\n2️⃣ امسح الكاش\n3️⃣ حدّث للإصدار الأخير\n\nلو المشكلة استمرت، رجع لنا.",
    industries: ["general"],
  },
  {
    id: "qr-support-troubleshoot-en",
    title: "Troubleshooting Steps",
    type: "quick_reply",
    category: "support",
    language: "en",
    body: "Try these steps to resolve the issue:\n1️⃣ Restart the app\n2️⃣ Clear the cache\n3️⃣ Update to the latest version\n\nLet us know if the issue persists.",
    industries: ["general"],
  },
  {
    id: "qr-support-ticket-ar",
    title: "Support Ticket Created",
    type: "quick_reply",
    category: "support",
    language: "ar",
    body: "تم فتح تذكرة دعم رقم {{ticket_id}} لمشكلتك. هيتواصل معك أحد من فريقنا خلال {{hours}} ساعات.",
    industries: ["general"],
  },
  {
    id: "qr-support-ticket-en",
    title: "Support Ticket Created",
    type: "quick_reply",
    category: "support",
    language: "en",
    body: "Support ticket #{{ticket_id}} has been created. A team member will contact you within {{hours}} hours.",
    industries: ["general"],
  },

  // ── QUICK-REPLY: CLOSING ──────────────────────────────────────────────────
  {
    id: "qr-closing-resolved-ar",
    title: "Issue Resolved",
    type: "quick_reply",
    category: "closing",
    language: "ar",
    body: "تم حل مشكلتك بنجاح! 🎉 لو عندك أي استفسار تاني أنا هنا.",
    industries: ["general"],
  },
  {
    id: "qr-closing-resolved-en",
    title: "Issue Resolved",
    type: "quick_reply",
    category: "closing",
    language: "en",
    body: "Your issue has been resolved! 🎉 If you have any other questions, I'm here to help.",
    industries: ["general"],
  },
  {
    id: "qr-closing-thankyou-ar",
    title: "Thank You & Goodbye",
    type: "quick_reply",
    category: "closing",
    language: "ar",
    body: "شكراً على تواصلك معنا {{name}}! يسعدنا دائماً خدمتك. وداعاً! 👋",
    industries: ["general"],
  },
  {
    id: "qr-closing-thankyou-en",
    title: "Thank You & Goodbye",
    type: "quick_reply",
    category: "closing",
    language: "en",
    body: "Thank you for contacting us {{name}}! It's always a pleasure serving you. Goodbye! 👋",
    industries: ["general"],
  },

  // ── QUICK-REPLY: HANDOFF ──────────────────────────────────────────────────
  {
    id: "qr-handoff-agent-ar",
    title: "Agent Transfer",
    type: "quick_reply",
    category: "handoff",
    language: "ar",
    body: "هحولك لـ {{agent_name}} اللي هيكمل معك. لحظة من فضلك... 🔀",
    industries: ["general"],
  },
  {
    id: "qr-handoff-agent-en",
    title: "Agent Transfer",
    type: "quick_reply",
    category: "handoff",
    language: "en",
    body: "I'm transferring you to {{agent_name}} who will continue assisting you. One moment please... 🔀",
    industries: ["general"],
  },
  {
    id: "qr-handoff-dept-ar",
    title: "Department Transfer",
    type: "quick_reply",
    category: "handoff",
    language: "ar",
    body: "بناءً على استفسارك، هحولك لقسم {{department}}. هيتواصل معك متخصص قريباً.",
    industries: ["general"],
  },
  {
    id: "qr-handoff-dept-en",
    title: "Department Transfer",
    type: "quick_reply",
    category: "handoff",
    language: "en",
    body: "Based on your inquiry, I'm transferring you to the {{department}} department. A specialist will be with you shortly.",
    industries: ["general"],
  },

  // ── QUICK-REPLY: OUT OF HOURS ─────────────────────────────────────────────
  {
    id: "qr-ooh-standard-ar",
    title: "Outside Business Hours",
    type: "quick_reply",
    category: "out_of_hours",
    language: "ar",
    body: "شكراً لتواصلك! ساعات عملنا من {{start_time}} لـ {{end_time}}. هيرد عليك أحد من فريقنا في أقرب وقت.",
    industries: ["general"],
  },
  {
    id: "qr-ooh-standard-en",
    title: "Outside Business Hours",
    type: "quick_reply",
    category: "out_of_hours",
    language: "en",
    body: "Thanks for reaching out! Our hours are {{start_time}} to {{end_time}}. A team member will get back to you as soon as possible.",
    industries: ["general"],
  },
  {
    id: "qr-ooh-holiday-ar",
    title: "Holiday Notice",
    type: "quick_reply",
    category: "out_of_hours",
    language: "ar",
    body: "نحن في إجازة {{holiday_name}} ونعود {{return_date}}. شكراً لتفهمك! 🎉",
    industries: ["general"],
  },
  {
    id: "qr-ooh-holiday-en",
    title: "Holiday Notice",
    type: "quick_reply",
    category: "out_of_hours",
    language: "en",
    body: "We're on {{holiday_name}} holiday and will return on {{return_date}}. Thank you for your understanding! 🎉",
    industries: ["general"],
  },
];

export const LIBRARY_TEMPLATES: LibraryTemplate[] = RAW.map((t) => ({
  ...t,
  variables: vars(t.body),
}));
