export type TimezoneEntry = {
  value: string;
  labelAr: string;
  labelEn: string;
  region: string;
};

export const TIMEZONES: TimezoneEntry[] = [
  { value: "Pacific/Midway", labelAr: "ميدواي", labelEn: "Midway", region: "Pacific" },
  { value: "Pacific/Niue", labelAr: "نييوي", labelEn: "Niue", region: "Pacific" },
  { value: "Pacific/Pago_Pago", labelAr: "باغو باغو", labelEn: "Pago Pago", region: "Pacific" },
  { value: "Pacific/Honolulu", labelAr: "هونولولو", labelEn: "Honolulu", region: "Pacific" },
  { value: "Pacific/Rarotonga", labelAr: "راروتونغا", labelEn: "Rarotonga", region: "Pacific" },
  { value: "Pacific/Tahiti", labelAr: "تاهيتي", labelEn: "Tahiti", region: "Pacific" },
  { value: "Pacific/Marquesas", labelAr: "ماركيساس", labelEn: "Marquesas", region: "Pacific" },
  { value: "America/Adak", labelAr: "أداك", labelEn: "Adak", region: "America" },
  { value: "Pacific/Gambier", labelAr: "غامبيير", labelEn: "Gambier", region: "Pacific" },
  { value: "America/Anchorage", labelAr: "أنكوريج", labelEn: "Anchorage", region: "America" },
  { value: "America/Juneau", labelAr: "جونو", labelEn: "Juneau", region: "America" },
  { value: "America/Sitka", labelAr: "سيتكا", labelEn: "Sitka", region: "America" },
  { value: "America/Metlakatla", labelAr: "ميتلاكاتلا", labelEn: "Metlakatla", region: "America" },
  { value: "America/Yakutat", labelAr: "ياكوتات", labelEn: "Yakutat", region: "America" },
  { value: "America/Nome", labelAr: "نوم", labelEn: "Nome", region: "America" },
  { value: "America/Vancouver", labelAr: "فانكوفر", labelEn: "Vancouver", region: "America" },
  { value: "America/Tijuana", labelAr: "تيخوانا", labelEn: "Tijuana", region: "America" },
  { value: "America/Los_Angeles", labelAr: "لوس أنجلوس", labelEn: "Los Angeles", region: "America" },
  { value: "America/Whitehorse", labelAr: "وايت هورس", labelEn: "Whitehorse", region: "America" },
  { value: "America/Dawson", labelAr: "دوسن", labelEn: "Dawson", region: "America" },
  { value: "Pacific/Pitcairn", labelAr: "بيتكيرن", labelEn: "Pitcairn", region: "Pacific" },
  { value: "America/Boise", labelAr: "بويزي", labelEn: "Boise", region: "America" },
  { value: "America/Cambridge_Bay", labelAr: "كامبريدج باي", labelEn: "Cambridge Bay", region: "America" },
  { value: "America/Denver", labelAr: "دنفر", labelEn: "Denver", region: "America" },
  { value: "America/Edmonton", labelAr: "إدمونتون", labelEn: "Edmonton", region: "America" },
  { value: "America/Inuvik", labelAr: "إنوفيك", labelEn: "Inuvik", region: "America" },
  { value: "America/Ojinaga", labelAr: "أوهيناغا", labelEn: "Ojinaga", region: "America" },
  { value: "America/Yellowknife", labelAr: "يلونايف", labelEn: "Yellowknife", region: "America" },
  { value: "America/Mazatlan", labelAr: "مازاتلان", labelEn: "Mazatlan", region: "America" },
  { value: "America/Bahia_Banderas", labelAr: "بايا بانديراس", labelEn: "Bahia Banderas", region: "America" },
  { value: "America/Chihuahua", labelAr: "تشيهواهوا", labelEn: "Chihuahua", region: "America" },
  { value: "America/Creston", labelAr: "كريستون", labelEn: "Creston", region: "America" },
  { value: "America/Dawson_Creek", labelAr: "دوسن كريك", labelEn: "Dawson Creek", region: "America" },
  { value: "America/Fort_Nelson", labelAr: "فورت نيلسون", labelEn: "Fort Nelson", region: "America" },
  { value: "America/Hermosillo", labelAr: "يرموسيو", labelEn: "Hermosillo", region: "America" },
  { value: "America/Phoenix", labelAr: "فينيكس", labelEn: "Phoenix", region: "America" },
  { value: "America/Belize", labelAr: "بليز", labelEn: "Belize", region: "America" },
  { value: "America/Chicago", labelAr: "شيكاغو", labelEn: "Chicago", region: "America" },
  { value: "America/Indiana/Knox", labelAr: "نوكس", labelEn: "Knox", region: "America" },
  { value: "America/Indiana/Tell_City", labelAr: "تيل سيتي", labelEn: "Tell City", region: "America" },
  { value: "America/Matamoros", labelAr: "ماتاموروس", labelEn: "Matamoros", region: "America" },
  { value: "America/Menominee", labelAr: "مينوميني", labelEn: "Menominee", region: "America" },
  { value: "America/North_Dakota/Beulah", labelAr: "بيولا", labelEn: "Beulah", region: "America" },
  { value: "America/North_Dakota/Center", labelAr: "سنتر", labelEn: "Center", region: "America" },
  { value: "America/North_Dakota/New_Salem", labelAr: "نيو سالم", labelEn: "New Salem", region: "America" },
  { value: "America/Rainy_River", labelAr: "ريني ريفر", labelEn: "Rainy River", region: "America" },
  { value: "America/Rankin_Inlet", labelAr: "رانكين إنليت", labelEn: "Rankin Inlet", region: "America" },
  { value: "America/Resolute", labelAr: "ريسولوت", labelEn: "Resolute", region: "America" },
  { value: "America/Winnipeg", labelAr: "وينيبيغ", labelEn: "Winnipeg", region: "America" },
  { value: "America/Merida", labelAr: "ميريدا", labelEn: "Merida", region: "America" },
  { value: "America/Mexico_City", labelAr: "مدينة المكسيك", labelEn: "Mexico City", region: "America" },
  { value: "America/Monterrey", labelAr: "مونتيري", labelEn: "Monterrey", region: "America" },
  { value: "America/Cancun", labelAr: "كانكون", labelEn: "Cancun", region: "America" },
  { value: "America/Bogota", labelAr: "بوغوتا", labelEn: "Bogota", region: "America" },
  { value: "America/Cayman", labelAr: "كايمان", labelEn: "Cayman", region: "America" },
  { value: "America/Costa_Rica", labelAr: "كوستاريكا", labelEn: "Costa Rica", region: "America" },
  { value: "America/El_Salvador", labelAr: "السلفادور", labelEn: "El Salvador", region: "America" },
  { value: "America/Guatemala", labelAr: "غواتيمالا", labelEn: "Guatemala", region: "America" },
  { value: "America/Managua", labelAr: "ماناغوا", labelEn: "Managua", region: "America" },
  { value: "America/Panama", labelAr: "بنما", labelEn: "Panama", region: "America" },
  { value: "America/Grand_Turk", labelAr: "غراند تورك", labelEn: "Grand Turk", region: "America" },
  { value: "America/Havana", labelAr: "هافانا", labelEn: "Havana", region: "America" },
  { value: "America/Port-au-Prince", labelAr: "بورت أو برنس", labelEn: "Port-au-Prince", region: "America" },
  { value: "America/Jamaica", labelAr: "جامايكا", labelEn: "Jamaica", region: "America" },
  { value: "America/Nassau", labelAr: "ناساو", labelEn: "Nassau", region: "America" },
  { value: "America/New_York", labelAr: "نيويورك", labelEn: "New York", region: "America" },
  { value: "America/Nipigon", labelAr: "نيبيغون", labelEn: "Nipigon", region: "America" },
  { value: "America/Pangnirtung", labelAr: "بانغنيرتونغ", labelEn: "Pangnirtung", region: "America" },
  { value: "America/Thunder_Bay", labelAr: "ثندر باي", labelEn: "Thunder Bay", region: "America" },
  { value: "America/Toronto", labelAr: "تورنتو", labelEn: "Toronto", region: "America" },
  { value: "America/Atikokan", labelAr: "أتيكوكان", labelEn: "Atikokan", region: "America" },
  { value: "America/Detroit", labelAr: "ديترويت", labelEn: "Detroit", region: "America" },
  { value: "America/Fort_Wayne", labelAr: "فورت واين", labelEn: "Fort Wayne", region: "America" },
  { value: "America/Indiana/Indianapolis", labelAr: "إنديانابوليس", labelEn: "Indianapolis", region: "America" },
  { value: "America/Indiana/Marengo", labelAr: "مارينغو", labelEn: "Marengo", region: "America" },
  { value: "America/Indiana/Petersburg", labelAr: "بيترسبورغ", labelEn: "Petersburg", region: "America" },
  { value: "America/Indiana/Vevay", labelAr: "فيفاي", labelEn: "Vevay", region: "America" },
  { value: "America/Indiana/Vincennes", labelAr: "فينسينز", labelEn: "Vincennes", region: "America" },
  { value: "America/Indiana/Winamac", labelAr: "ويناماك", labelEn: "Winamac", region: "America" },
  { value: "America/Kentucky/Louisville", labelAr: "لويفيل", labelEn: "Louisville", region: "America" },
  { value: "America/Kentucky/Monticello", labelAr: "مونتيسيلو", labelEn: "Monticello", region: "America" },
  { value: "America/Iqaluit", labelAr: "إيكالويت", labelEn: "Iqaluit", region: "America" },
  { value: "America/Montreal", labelAr: "مونتريال", labelEn: "Montreal", region: "America" },
  { value: "America/Barbados", labelAr: "باربادوس", labelEn: "Barbados", region: "America" },
  { value: "America/Curacao", labelAr: "كوراساو", labelEn: "Curacao", region: "America" },
  { value: "America/Port_of_Spain", labelAr: "بورت أوف سبين", labelEn: "Port of Spain", region: "America" },
  { value: "America/Puerto_Rico", labelAr: "بورتوريكو", labelEn: "Puerto Rico", region: "America" },
  { value: "America/Santo_Domingo", labelAr: "سانتو دومينغو", labelEn: "Santo Domingo", region: "America" },
  { value: "America/St_Thomas", labelAr: "سان توماس", labelEn: "St. Thomas", region: "America" },
  { value: "America/St_Lucia", labelAr: "سانت لوسيا", labelEn: "St. Lucia", region: "America" },
  { value: "America/St_Kitts", labelAr: "سان كيتس", labelEn: "St. Kitts", region: "America" },
  { value: "America/St_Vincent", labelAr: "سان فينسنت", labelEn: "St. Vincent", region: "America" },
  { value: "America/Grenada", labelAr: "غرينادا", labelEn: "Grenada", region: "America" },
  { value: "America/Anguilla", labelAr: "أنغويلا", labelEn: "Anguilla", region: "America" },
  { value: "America/Antigua", labelAr: "أنتيغوا", labelEn: "Antigua", region: "America" },
  { value: "America/Dominica", labelAr: "دومينيكا", labelEn: "Dominica", region: "America" },
  { value: "America/Marigot", labelAr: "ماريغو", labelEn: "Marigot", region: "America" },
  { value: "America/Montserrat", labelAr: "مونتسرات", labelEn: "Montserrat", region: "America" },
  { value: "America/St_Barthelemy", labelAr: "سان بارتيلمي", labelEn: "St. Barthelemy", region: "America" },
  { value: "America/Halifax", labelAr: "هاليفاكس", labelEn: "Halifax", region: "America" },
  { value: "America/Glace_Bay", labelAr: "غلاس باي", labelEn: "Glace Bay", region: "America" },
  { value: "America/Goose_Bay", labelAr: "غوس باي", labelEn: "Goose Bay", region: "America" },
  { value: "America/Moncton", labelAr: "مونكتون", labelEn: "Moncton", region: "America" },
  { value: "America/Bermuda", labelAr: "برمودا", labelEn: "Bermuda", region: "America" },
  { value: "Atlantic/Stanley", labelAr: "ستانلي", labelEn: "Stanley", region: "Atlantic" },
  { value: "America/Argentina/Buenos_Aires", labelAr: "بوينس آيرس", labelEn: "Buenos Aires", region: "America" },
  { value: "America/Argentina/Cordoba", labelAr: "كوردوبا", labelEn: "Cordoba", region: "America" },
  { value: "America/Argentina/Salta", labelAr: "سالتا", labelEn: "Salta", region: "America" },
  { value: "America/Argentina/Jujuy", labelAr: "خوخوي", labelEn: "Jujuy", region: "America" },
  { value: "America/Argentina/Tucuman", labelAr: "توكومان", labelEn: "Tucuman", region: "America" },
  { value: "America/Argentina/Catamarca", labelAr: "كاتاماركا", labelEn: "Catamarca", region: "America" },
  { value: "America/Argentina/La_Rioja", labelAr: "لا ريوخا", labelEn: "La Rioja", region: "America" },
  { value: "America/Argentina/San_Juan", labelAr: "سان خوان", labelEn: "San Juan", region: "America" },
  { value: "America/Argentina/Mendoza", labelAr: "مندوزا", labelEn: "Mendoza", region: "America" },
  { value: "America/Argentina/San_Luis", labelAr: "سان لويس", labelEn: "San Luis", region: "America" },
  { value: "America/Argentina/Rio_Gallegos", labelAr: "ريو غاليغوس", labelEn: "Rio Gallegos", region: "America" },
  { value: "America/Argentina/Ushuaia", labelAr: "أوشوايا", labelEn: "Ushuaia", region: "America" },
  { value: "America/Aruba", labelAr: "أروبا", labelEn: "Aruba", region: "America" },
  { value: "America/Asuncion", labelAr: "أسونسيون", labelEn: "Asuncion", region: "America" },
  { value: "America/Belem", labelAr: "بيليم", labelEn: "Belem", region: "America" },
  { value: "America/Campo_Grande", labelAr: "كامبو غراندي", labelEn: "Campo Grande", region: "America" },
  { value: "America/Cuiaba", labelAr: "كويابا", labelEn: "Cuiaba", region: "America" },
  { value: "America/Fortaleza", labelAr: "فورتاليزا", labelEn: "Fortaleza", region: "America" },
  { value: "America/Maceio", labelAr: "ماسايو", labelEn: "Maceio", region: "America" },
  { value: "America/Manaus", labelAr: "ماناوس", labelEn: "Manaus", region: "America" },
  { value: "America/Noronha", labelAr: "نورونيا", labelEn: "Noronha", region: "America" },
  { value: "America/Recife", labelAr: "ريسيفي", labelEn: "Recife", region: "America" },
  { value: "America/Rio_Branco", labelAr: "ريو برانكو", labelEn: "Rio Branco", region: "America" },
  { value: "America/Santarem", labelAr: "سانتاريم", labelEn: "Santarem", region: "America" },
  { value: "America/Sao_Paulo", labelAr: "ساو باولو", labelEn: "Sao Paulo", region: "America" },
  { value: "America/Bahia", labelAr: "باهيا", labelEn: "Bahia", region: "America" },
  { value: "America/Cayenne", labelAr: "كاين", labelEn: "Cayenne", region: "America" },
  { value: "America/Guyana", labelAr: "غيانا", labelEn: "Guyana", region: "America" },
  { value: "America/Paramaribo", labelAr: "باراماريبو", labelEn: "Paramaribo", region: "America" },
  { value: "America/Miquelon", labelAr: "ميكلون", labelEn: "Miquelon", region: "America" },
  { value: "America/Montevideo", labelAr: "مونتيفيديو", labelEn: "Montevideo", region: "America" },
  { value: "America/Caracas", labelAr: "كاراكاس", labelEn: "Caracas", region: "America" },
  { value: "Atlantic/Azores", labelAr: "الأزور", labelEn: "Azores", region: "Atlantic" },
  { value: "Atlantic/Cape_Verde", labelAr: "الرأس الأخضر", labelEn: "Cape Verde", region: "Atlantic" },
  { value: "Atlantic/South_Georgia", labelAr: "جورجيا الجنوبية", labelEn: "South Georgia", region: "Atlantic" },
  { value: "Atlantic/Reykjavik", labelAr: "ريكيافيك", labelEn: "Reykjavik", region: "Atlantic" },
  { value: "Atlantic/St_Helena", labelAr: "سانت هيلينا", labelEn: "St. Helena", region: "Atlantic" },
  { value: "Atlantic/Faroe", labelAr: "جزر فارو", labelEn: "Faroe", region: "Atlantic" },
  { value: "Atlantic/Canary", labelAr: "جزر الكناري", labelEn: "Canary", region: "Atlantic" },
  { value: "Atlantic/Madeira", labelAr: "ماديرا", labelEn: "Madeira", region: "Atlantic" },
  { value: "Africa/Abidjan", labelAr: "أبيدجان", labelEn: "Abidjan", region: "Africa" },
  { value: "Africa/Accra", labelAr: "أكرا", labelEn: "Accra", region: "Africa" },
  { value: "Africa/Bissau", labelAr: "بيساو", labelEn: "Bissau", region: "Africa" },
  { value: "Africa/Monrovia", labelAr: "مونروفيا", labelEn: "Monrovia", region: "Africa" },
  { value: "Africa/Sao_Tome", labelAr: "ساو تومي", labelEn: "Sao Tome", region: "Africa" },
  { value: "Africa/Algiers", labelAr: "الجزائر", labelEn: "Algiers", region: "Africa" },
  { value: "Africa/Bangui", labelAr: "بانغي", labelEn: "Bangui", region: "Africa" },
  { value: "Africa/Brazzaville", labelAr: "برازافيل", labelEn: "Brazzaville", region: "Africa" },
  { value: "Africa/Casablanca", labelAr: "الدار البيضاء", labelEn: "Casablanca", region: "Africa" },
  { value: "Africa/Douala", labelAr: "دوالا", labelEn: "Douala", region: "Africa" },
  { value: "Africa/Kinshasa", labelAr: "كينشاسا", labelEn: "Kinshasa", region: "Africa" },
  { value: "Africa/Lagos", labelAr: "لاغوس", labelEn: "Lagos", region: "Africa" },
  { value: "Africa/Libreville", labelAr: "ليبرفيل", labelEn: "Libreville", region: "Africa" },
  { value: "Africa/Luanda", labelAr: "لواندا", labelEn: "Luanda", region: "Africa" },
  { value: "Africa/Malabo", labelAr: "مالابو", labelEn: "Malabo", region: "Africa" },
  { value: "Africa/Ndjamena", labelAr: "نجامينا", labelEn: "Ndjamena", region: "Africa" },
  { value: "Africa/Niamey", labelAr: "نيامي", labelEn: "Niamey", region: "Africa" },
  { value: "Africa/Porto-Novo", labelAr: "بورتو نوفو", labelEn: "Porto-Novo", region: "Africa" },
  { value: "Africa/Tunis", labelAr: "تونس", labelEn: "Tunis", region: "Africa" },
  { value: "Africa/Cairo", labelAr: "القاهرة", labelEn: "Cairo", region: "Africa" },
  { value: "Africa/El_Aaiun", labelAr: "العيون", labelEn: "El Aaiun", region: "Africa" },
  { value: "Africa/Johannesburg", labelAr: "جوهانسبرغ", labelEn: "Johannesburg", region: "Africa" },
  { value: "Africa/Maputo", labelAr: "مابوتو", labelEn: "Maputo", region: "Africa" },
  { value: "Africa/Blantyre", labelAr: "بلانتاير", labelEn: "Blantyre", region: "Africa" },
  { value: "Africa/Bujumbura", labelAr: "بوجومبورا", labelEn: "Bujumbura", region: "Africa" },
  { value: "Africa/Gaborone", labelAr: "غابورون", labelEn: "Gaborone", region: "Africa" },
  { value: "Africa/Harare", labelAr: "هراري", labelEn: "Harare", region: "Africa" },
  { value: "Africa/Kigali", labelAr: "كيغالي", labelEn: "Kigali", region: "Africa" },
  { value: "Africa/Lubumbashi", labelAr: "لوبومباشي", labelEn: "Lubumbashi", region: "Africa" },
  { value: "Africa/Lusaka", labelAr: "لوساكا", labelEn: "Lusaka", region: "Africa" },
  { value: "Africa/Windhoek", labelAr: "ويندهوك", labelEn: "Windhoek", region: "Africa" },
  { value: "Africa/Addis_Ababa", labelAr: "أديس أبابا", labelEn: "Addis Ababa", region: "Africa" },
  { value: "Africa/Asmara", labelAr: "أسمرة", labelEn: "Asmara", region: "Africa" },
  { value: "Africa/Dar_es_Salaam", labelAr: "دار السلام", labelEn: "Dar es Salaam", region: "Africa" },
  { value: "Africa/Kampala", labelAr: "كامبالا", labelEn: "Kampala", region: "Africa" },
  { value: "Africa/Mogadishu", labelAr: "مقديشو", labelEn: "Mogadishu", region: "Africa" },
  { value: "Africa/Nairobi", labelAr: "نيروبي", labelEn: "Nairobi", region: "Africa" },
  { value: "Africa/Djibouti", labelAr: "جيبوتي", labelEn: "Djibouti", region: "Africa" },
  { value: "Africa/Khartoum", labelAr: "الخرطوم", labelEn: "Khartoum", region: "Africa" },
  { value: "Europe/London", labelAr: "لندن", labelEn: "London", region: "Europe" },
  { value: "Europe/Dublin", labelAr: "دبلن", labelEn: "Dublin", region: "Europe" },
  { value: "Europe/Lisbon", labelAr: "لشبونة", labelEn: "Lisbon", region: "Europe" },
  { value: "Europe/Andorra", labelAr: "أندورا", labelEn: "Andorra", region: "Europe" },
  { value: "Europe/Berlin", labelAr: "برلين", labelEn: "Berlin", region: "Europe" },
  { value: "Europe/Zurich", labelAr: "زيورخ", labelEn: "Zurich", region: "Europe" },
  { value: "Europe/Vienna", labelAr: "فيينا", labelEn: "Vienna", region: "Europe" },
  { value: "Europe/Brussels", labelAr: "بروكسل", labelEn: "Brussels", region: "Europe" },
  { value: "Europe/Copenhagen", labelAr: "كوبنهاغن", labelEn: "Copenhagen", region: "Europe" },
  { value: "Europe/Madrid", labelAr: "مدريد", labelEn: "Madrid", region: "Europe" },
  { value: "Europe/Paris", labelAr: "باريس", labelEn: "Paris", region: "Europe" },
  { value: "Europe/Rome", labelAr: "روما", labelEn: "Rome", region: "Europe" },
  { value: "Europe/Amsterdam", labelAr: "أمستردام", labelEn: "Amsterdam", region: "Europe" },
  { value: "Europe/Oslo", labelAr: "أوسلو", labelEn: "Oslo", region: "Europe" },
  { value: "Europe/Stockholm", labelAr: "ستوكهولم", labelEn: "Stockholm", region: "Europe" },
  { value: "Europe/Budapest", labelAr: "بودابست", labelEn: "Budapest", region: "Europe" },
  { value: "Europe/Prague", labelAr: "براغ", labelEn: "Prague", region: "Europe" },
  { value: "Europe/Belgrade", labelAr: "بلغراد", labelEn: "Belgrade", region: "Europe" },
  { value: "Europe/Bratislava", labelAr: "براتيسلافا", labelEn: "Bratislava", region: "Europe" },
  { value: "Europe/Ljubljana", labelAr: "ليوبليانا", labelEn: "Ljubljana", region: "Europe" },
  { value: "Europe/Warsaw", labelAr: "وارسو", labelEn: "Warsaw", region: "Europe" },
  { value: "Europe/Sarajevo", labelAr: "سراييفو", labelEn: "Sarajevo", region: "Europe" },
  { value: "Europe/Skopje", labelAr: "سكوبي", labelEn: "Skopje", region: "Europe" },
  { value: "Europe/Zagreb", labelAr: "زغرب", labelEn: "Zagreb", region: "Europe" },
  { value: "Europe/Podgorica", labelAr: "بودغوريتسا", labelEn: "Podgorica", region: "Europe" },
  { value: "Europe/Tirane", labelAr: "تيرانا", labelEn: "Tirane", region: "Europe" },
  { value: "Europe/Athens", labelAr: "أثينا", labelEn: "Athens", region: "Europe" },
  { value: "Europe/Bucharest", labelAr: "بوخارست", labelEn: "Bucharest", region: "Europe" },
  { value: "Europe/Chisinau", labelAr: "كيشيناو", labelEn: "Chisinau", region: "Europe" },
  { value: "Europe/Helsinki", labelAr: "هلسنكي", labelEn: "Helsinki", region: "Europe" },
  { value: "Europe/Kiev", labelAr: "كييف", labelEn: "Kyiv", region: "Europe" },
  { value: "Europe/Riga", labelAr: "ريغا", labelEn: "Riga", region: "Europe" },
  { value: "Europe/Sofia", labelAr: "صوفيا", labelEn: "Sofia", region: "Europe" },
  { value: "Europe/Tallinn", labelAr: "تالين", labelEn: "Tallinn", region: "Europe" },
  { value: "Europe/Vilnius", labelAr: "فيلنيوس", labelEn: "Vilnius", region: "Europe" },
  { value: "Europe/Uzhgorod", labelAr: "أوجهورود", labelEn: "Uzhgorod", region: "Europe" },
  { value: "Europe/Zaporozhye", labelAr: "زابوروجي", labelEn: "Zaporozhye", region: "Europe" },
  { value: "Europe/Istanbul", labelAr: "إسطنبول", labelEn: "Istanbul", region: "Europe" },
  { value: "Europe/Minsk", labelAr: "مينسك", labelEn: "Minsk", region: "Europe" },
  { value: "Europe/Moscow", labelAr: "موسكو", labelEn: "Moscow", region: "Europe" },
  { value: "Europe/Simferopol", labelAr: "سيمفروبول", labelEn: "Simferopol", region: "Europe" },
  { value: "Europe/Volgograd", labelAr: "فولغوغراد", labelEn: "Volgograd", region: "Europe" },
  { value: "Europe/Samara", labelAr: "سامارا", labelEn: "Samara", region: "Europe" },
  { value: "Europe/Kirov", labelAr: "كيروف", labelEn: "Kirov", region: "Europe" },
  { value: "Europe/Astrakhan", labelAr: "أستراخان", labelEn: "Astrakhan", region: "Europe" },
  { value: "Europe/Saratov", labelAr: "ساراتوف", labelEn: "Saratov", region: "Europe" },
  { value: "Europe/Kaliningrad", labelAr: "كالينينغراد", labelEn: "Kaliningrad", region: "Europe" },
  { value: "Europe/Mariehamn", labelAr: "ماريهامن", labelEn: "Mariehamn", region: "Europe" },
  { value: "Europe/Guernsey", labelAr: "غيرنزي", labelEn: "Guernsey", region: "Europe" },
  { value: "Europe/Jersey", labelAr: "جيرزي", labelEn: "Jersey", region: "Europe" },
  { value: "Europe/Isle_of_Man", labelAr: "جزيرة مان", labelEn: "Isle of Man", region: "Europe" },
  { value: "Europe/Malta", labelAr: "مالطا", labelEn: "Malta", region: "Europe" },
  { value: "Europe/Monaco", labelAr: "موناكو", labelEn: "Monaco", region: "Europe" },
  { value: "Europe/Luxembourg", labelAr: "لوكسمبورغ", labelEn: "Luxembourg", region: "Europe" },
  { value: "Europe/San_Marino", labelAr: "سان مارينو", labelEn: "San Marino", region: "Europe" },
  { value: "Europe/Vatican", labelAr: "الفاتيكان", labelEn: "Vatican", region: "Europe" },
  { value: "Asia/Nicosia", labelAr: "نيقوسيا", labelEn: "Nicosia", region: "Asia" },
  { value: "Asia/Famagusta", labelAr: "فاماغوستا", labelEn: "Famagusta", region: "Asia" },
  { value: "Asia/Beirut", labelAr: "بيروت", labelEn: "Beirut", region: "Asia" },
  { value: "Asia/Damascus", labelAr: "دمشق", labelEn: "Damascus", region: "Asia" },
  { value: "Asia/Amman", labelAr: "عمّان", labelEn: "Amman", region: "Asia" },
  { value: "Asia/Jerusalem", labelAr: "القدس", labelEn: "Jerusalem", region: "Asia" },
  { value: "Asia/Gaza", labelAr: "غزة", labelEn: "Gaza", region: "Asia" },
  { value: "Asia/Hebron", labelAr: "الخليل", labelEn: "Hebron", region: "Asia" },
  { value: "Asia/Istanbul", labelAr: "إسطنبول", labelEn: "Istanbul", region: "Asia" },
  { value: "Asia/Baghdad", labelAr: "بغداد", labelEn: "Baghdad", region: "Asia" },
  { value: "Asia/Kuwait", labelAr: "الكويت", labelEn: "Kuwait", region: "Asia" },
  { value: "Asia/Riyadh", labelAr: "الرياض", labelEn: "Riyadh", region: "Asia" },
  { value: "Asia/Bahrain", labelAr: "البحرين", labelEn: "Bahrain", region: "Asia" },
  { value: "Asia/Qatar", labelAr: "قطر", labelEn: "Qatar", region: "Asia" },
  { value: "Asia/Aden", labelAr: "عدن", labelEn: "Aden", region: "Asia" },
  { value: "Asia/Dubai", labelAr: "دبي", labelEn: "Dubai", region: "Asia" },
  { value: "Asia/Muscat", labelAr: "مسقط", labelEn: "Muscat", region: "Asia" },
  { value: "Asia/Tehran", labelAr: "طهران", labelEn: "Tehran", region: "Asia" },
  { value: "Asia/Baku", labelAr: "باكو", labelEn: "Baku", region: "Asia" },
  { value: "Asia/Tbilisi", labelAr: "تبليسي", labelEn: "Tbilisi", region: "Asia" },
  { value: "Asia/Yerevan", labelAr: "يريفان", labelEn: "Yerevan", region: "Asia" },
  { value: "Asia/Tashkent", labelAr: "طشقند", labelEn: "Tashkent", region: "Asia" },
  { value: "Asia/Samarkand", labelAr: "سمرقند", labelEn: "Samarkand", region: "Asia" },
  { value: "Asia/Dushanbe", labelAr: "دوشنبه", labelEn: "Dushanbe", region: "Asia" },
  { value: "Asia/Ashgabat", labelAr: "عشق آباد", labelEn: "Ashgabat", region: "Asia" },
  { value: "Asia/Aqtau", labelAr: "أقتاو", labelEn: "Aqtau", region: "Asia" },
  { value: "Asia/Aqtobe", labelAr: "أكتوب", labelEn: "Aqtobe", region: "Asia" },
  { value: "Asia/Atyrau", labelAr: "أتيرو", labelEn: "Atyrau", region: "Asia" },
  { value: "Asia/Oral", labelAr: "أورال", labelEn: "Oral", region: "Asia" },
  { value: "Asia/Qyzylorda", labelAr: "كيزيلوردا", labelEn: "Qyzylorda", region: "Asia" },
  { value: "Asia/Almaty", labelAr: "ألماتي", labelEn: "Almaty", region: "Asia" },
  { value: "Asia/Qostanay", labelAr: "كوستناي", labelEn: "Qostanay", region: "Asia" },
  { value: "Asia/Karachi", labelAr: "كراتشي", labelEn: "Karachi", region: "Asia" },
  { value: "Asia/Colombo", labelAr: "كولومبو", labelEn: "Colombo", region: "Asia" },
  { value: "Asia/Calcutta", labelAr: "كولكاتا", labelEn: "Kolkata", region: "Asia" },
  { value: "Asia/Kathmandu", labelAr: "كاتماندو", labelEn: "Kathmandu", region: "Asia" },
  { value: "Asia/Dhaka", labelAr: "دكا", labelEn: "Dhaka", region: "Asia" },
  { value: "Asia/Thimphu", labelAr: "تيمفو", labelEn: "Thimphu", region: "Asia" },
  { value: "Asia/Urumqi", labelAr: "أورومتشي", labelEn: "Urumqi", region: "Asia" },
  { value: "Asia/Omsk", labelAr: "أومسك", labelEn: "Omsk", region: "Asia" },
  { value: "Asia/Novosibirsk", labelAr: "نوفوسيبيرسك", labelEn: "Novosibirsk", region: "Asia" },
  { value: "Asia/Barnaul", labelAr: "بارناول", labelEn: "Barnaul", region: "Asia" },
  { value: "Asia/Novokuznetsk", labelAr: "نوفوكوزنتسك", labelEn: "Novokuznetsk", region: "Asia" },
  { value: "Asia/Tomsk", labelAr: "تومسك", labelEn: "Tomsk", region: "Asia" },
  { value: "Asia/Krasnoyarsk", labelAr: "كراسنويارسك", labelEn: "Krasnoyarsk", region: "Asia" },
  { value: "Asia/Abakan", labelAr: "أباكان", labelEn: "Abakan", region: "Asia" },
  { value: "Asia/Kemerovo", labelAr: "كيميروفو", labelEn: "Kemerovo", region: "Asia" },
  { value: "Asia/Norilsk", labelAr: "نوريلسك", labelEn: "Norilsk", region: "Asia" },
  { value: "Asia/Yakutsk", labelAr: "ياكوتسك", labelEn: "Yakutsk", region: "Asia" },
  { value: "Asia/Irkutsk", labelAr: "إركوتسك", labelEn: "Irkutsk", region: "Asia" },
  { value: "Asia/Chita", labelAr: "تشيتا", labelEn: "Chita", region: "Asia" },
  { value: "Asia/Khandyga", labelAr: "خانديغا", labelEn: "Khandyga", region: "Asia" },
  { value: "Asia/Vladivostok", labelAr: "فلاديفوستوك", labelEn: "Vladivostok", region: "Asia" },
  { value: "Asia/Ust-Nera", labelAr: "أوست-نيرا", labelEn: "Ust-Nera", region: "Asia" },
  { value: "Asia/Magadan", labelAr: "ماغادان", labelEn: "Magadan", region: "Asia" },
  { value: "Asia/Sakhalin", labelAr: "ساخالين", labelEn: "Sakhalin", region: "Asia" },
  { value: "Asia/Srednekolymsk", labelAr: "سريدانكوليمسك", labelEn: "Srednekolymsk", region: "Asia" },
  { value: "Asia/Kamchatka", labelAr: "كامتشاتكا", labelEn: "Kamchatka", region: "Asia" },
  { value: "Asia/Anadyr", labelAr: "أنادير", labelEn: "Anadyr", region: "Asia" },
  { value: "Asia/Bangkok", labelAr: "بانكوك", labelEn: "Bangkok", region: "Asia" },
  { value: "Asia/Ho_Chi_Minh", labelAr: "هو تشي منه", labelEn: "Ho Chi Minh", region: "Asia" },
  { value: "Asia/Jakarta", labelAr: "جاكرتا", labelEn: "Jakarta", region: "Asia" },
  { value: "Asia/Pontianak", labelAr: "بونتياناك", labelEn: "Pontianak", region: "Asia" },
  { value: "Asia/Makassar", labelAr: "ماكاسار", labelEn: "Makassar", region: "Asia" },
  { value: "Asia/Kuala_Lumpur", labelAr: "كوالالمبور", labelEn: "Kuala Lumpur", region: "Asia" },
  { value: "Asia/Singapore", labelAr: "سنغافورة", labelEn: "Singapore", region: "Asia" },
  { value: "Asia/Manila", labelAr: "مانيلا", labelEn: "Manila", region: "Asia" },
  { value: "Asia/Brunei", labelAr: "بروناي", labelEn: "Brunei", region: "Asia" },
  { value: "Asia/Shanghai", labelAr: "شنغهاي", labelEn: "Shanghai", region: "Asia" },
  { value: "Asia/Taipei", labelAr: "تايبيه", labelEn: "Taipei", region: "Asia" },
  { value: "Asia/Hong_Kong", labelAr: "هونغ كونغ", labelEn: "Hong Kong", region: "Asia" },
  { value: "Asia/Macau", labelAr: "ماكاو", labelEn: "Macau", region: "Asia" },
  { value: "Asia/Pyongyang", labelAr: "بيونغ يانغ", labelEn: "Pyongyang", region: "Asia" },
  { value: "Asia/Seoul", labelAr: "سيول", labelEn: "Seoul", region: "Asia" },
  { value: "Asia/Tokyo", labelAr: "طوكيو", labelEn: "Tokyo", region: "Asia" },
  { value: "Asia/Dili", labelAr: "ديلي", labelEn: "Dili", region: "Asia" },
  { value: "Asia/Jayapura", labelAr: "جايابورا", labelEn: "Jayapura", region: "Asia" },
  { value: "Asia/Yangon", labelAr: "يانغون", labelEn: "Yangon", region: "Asia" },
  { value: "Asia/Hovd", labelAr: "خوفد", labelEn: "Hovd", region: "Asia" },
  { value: "Asia/Choibalsan", labelAr: "تشويبالسان", labelEn: "Choibalsan", region: "Asia" },
  { value: "Asia/Ulaanbaatar", labelAr: "أولان باتور", labelEn: "Ulaanbaatar", region: "Asia" },
  { value: "Asia/Kabul", labelAr: "كابول", labelEn: "Kabul", region: "Asia" },
  { value: "Asia/Yekaterinburg", labelAr: "يكاترينبورغ", labelEn: "Yekaterinburg", region: "Asia" },
  { value: "Pacific/Auckland", labelAr: "أوكلاند", labelEn: "Auckland", region: "Pacific" },
  { value: "Pacific/Fiji", labelAr: "فيجي", labelEn: "Fiji", region: "Pacific" },
  { value: "Pacific/Fakaofo", labelAr: "فاكاوفو", labelEn: "Fakaofo", region: "Pacific" },
  { value: "Pacific/Chatham", labelAr: "تشاتام", labelEn: "Chatham", region: "Pacific" },
  { value: "Pacific/Tongatapu", labelAr: "تونغاتابو", labelEn: "Tongatapu", region: "Pacific" },
  { value: "Pacific/Apia", labelAr: "أبيا", labelEn: "Apia", region: "Pacific" },
  { value: "Pacific/Norfolk", labelAr: "نورفولك", labelEn: "Norfolk", region: "Pacific" },
  { value: "Pacific/Lord_Howe", labelAr: "لورد هاو", labelEn: "Lord Howe", region: "Pacific" },
  { value: "Australia/Sydney", labelAr: "سيدني", labelEn: "Sydney", region: "Australia" },
  { value: "Australia/Melbourne", labelAr: "ملبورن", labelEn: "Melbourne", region: "Australia" },
  { value: "Australia/Brisbane", labelAr: "بريزبان", labelEn: "Brisbane", region: "Australia" },
  { value: "Australia/Perth", labelAr: "بيرث", labelEn: "Perth", region: "Australia" },
  { value: "Australia/Adelaide", labelAr: "أديلايد", labelEn: "Adelaide", region: "Australia" },
  { value: "Australia/Hobart", labelAr: "هوبارت", labelEn: "Hobart", region: "Australia" },
  { value: "Australia/Darwin", labelAr: "داروين", labelEn: "Darwin", region: "Australia" },
  { value: "Australia/Lindeman", labelAr: "ليندمان", labelEn: "Lindeman", region: "Australia" },
  { value: "Australia/Broken_Hill", labelAr: "بروكن هيل", labelEn: "Broken Hill", region: "Australia" },
  { value: "Australia/Currie", labelAr: "كوري", labelEn: "Currie", region: "Australia" },
  { value: "Australia/Eucla", labelAr: "يوكلا", labelEn: "Eucla", region: "Australia" },
  { value: "Australia/Lord_Howe", labelAr: "لورد هاو", labelEn: "Lord Howe", region: "Australia" },
  { value: "Australia/Antipodes", labelAr: "أنتيبودس", labelEn: "Antipodes", region: "Australia" },
  { value: "Indian/Maldives", labelAr: "المالديف", labelEn: "Maldives", region: "Indian" },
  { value: "Indian/Chagos", labelAr: "تشاغوس", labelEn: "Chagos", region: "Indian" },
  { value: "Indian/Christmas", labelAr: "كريسماس", labelEn: "Christmas", region: "Indian" },
  { value: "Indian/Cocos", labelAr: "كوكوس", labelEn: "Cocos", region: "Indian" },
  { value: "Indian/Mahe", labelAr: "ماهيه", labelEn: "Mahe", region: "Indian" },
  { value: "Indian/Mauritius", labelAr: "موريشيوس", labelEn: "Mauritius", region: "Indian" },
  { value: "Indian/Reunion", labelAr: "ريونيون", labelEn: "Reunion", region: "Indian" },
  { value: "Indian/Kerguelen", labelAr: "كيرغولين", labelEn: "Kerguelen", region: "Indian" },
  { value: "Antarctica/McMurdo", labelAr: "مكموردو", labelEn: "McMurdo", region: "Antarctica" },
  { value: "Antarctica/DumontDUrville", labelAr: "ديمون دورفيل", labelEn: "Dumont d'Urville", region: "Antarctica" },
  { value: "Antarctica/Syowa", labelAr: "شووا", labelEn: "Syowa", region: "Antarctica" },
  { value: "Antarctica/Vostok", labelAr: "فوستوك", labelEn: "Vostok", region: "Antarctica" },
  { value: "Antarctica/Casey", labelAr: "كاسي", labelEn: "Casey", region: "Antarctica" },
  { value: "Antarctica/Davis", labelAr: "ديفيس", labelEn: "Davis", region: "Antarctica" },
  { value: "Antarctica/Mawson", labelAr: "موسون", labelEn: "Mawson", region: "Antarctica" },
  { value: "Antarctica/Palmer", labelAr: "بالمر", labelEn: "Palmer", region: "Antarctica" },
  { value: "Antarctica/Rothera", labelAr: "روثيرا", labelEn: "Rothera", region: "Antarctica" },
  { value: "Antarctica/Troll", labelAr: "ترول", labelEn: "Troll", region: "Antarctica" },
  { value: "Arctic/Longyearbyen", labelAr: "لونغييربين", labelEn: "Longyearbyen", region: "Arctic" },
];

const UTC_OFFSETS: Record<string, string> = {};
const _cache: Map<string, string> = new Map();

export function getUtcOffset(tz: string): string {
  const cached = _cache.get(tz);
  if (cached) return cached;
  try {
    const offset = new Intl.DateTimeFormat("en-US", {
      timeZone: tz,
      timeZoneName: "shortOffset",
    })
      .formatToParts(new Date())
      .find((p) => p.type === "timeZoneName")?.value ?? "";
    _cache.set(tz, offset);
    return offset;
  } catch {
    return "";
  }
}

export function getTimezoneLabel(tz: TimezoneEntry, locale: "ar" | "en"): string {
  const name = locale === "ar" ? tz.labelAr : tz.labelEn;
  const offset = getUtcOffset(tz.value);
  return `${name} (${offset})`;
}
